// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class AIS_ClearMode extends jcas.Standard_Enumeration  {

public final static short AIS_CM_All = 0;
public final static short AIS_CM_Interactive = 1;
public final static short AIS_CM_Filters = 2;
public final static short AIS_CM_StandardModes = 3;
public final static short AIS_CM_TemporaryShapePrs = 4;


  
}
