// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;

import jjAIS.TCollection_BasicMap;
import jcas.Standard_Integer;
import jjAIS.SelectMgr_EntityOwner;
import jjAIS.Prs3d_Presentation;
import jcas.Standard_Boolean;


public class AIS_IndexedDataMapOfOwnerPrs extends jjAIS.TCollection_BasicMap {

 static {
    System.loadLibrary("jjAIS");
 }
            
public AIS_IndexedDataMapOfOwnerPrs(int NbBuckets) {
   AIS_IndexedDataMapOfOwnerPrs_Create_1(NbBuckets);
}

private final native void AIS_IndexedDataMapOfOwnerPrs_Create_1(int NbBuckets);

native public final AIS_IndexedDataMapOfOwnerPrs Assign(AIS_IndexedDataMapOfOwnerPrs Other);
native public final void ReSize(int NbBuckets);
native public final void Clear();
native public final int Add(SelectMgr_EntityOwner K,Prs3d_Presentation I);
native public final void Substitute(int I,SelectMgr_EntityOwner K,Prs3d_Presentation T);
native public final void RemoveLast();
native public final boolean Contains(SelectMgr_EntityOwner K);
native public final SelectMgr_EntityOwner FindKey(int I);
native public final Prs3d_Presentation FindFromIndex(int I);
native public final Prs3d_Presentation ChangeFromIndex(int I);
native public final int FindIndex(SelectMgr_EntityOwner K);
native public final Prs3d_Presentation FindFromKey(SelectMgr_EntityOwner K);
native public final Prs3d_Presentation ChangeFromKey(SelectMgr_EntityOwner K);
public AIS_IndexedDataMapOfOwnerPrs() {
}



public native static void FinalizeValue(long anHID);

public void finalize() {
   synchronized(myCasLock) {
     if ( aVirer != 0 ) FinalizeValue(HID);
     HID = 0;
   }
}

}
