// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;

import jjAIS.TCollection_BasicMapIterator;
import jjAIS.AIS_MapOfInteractive;
import jjAIS.AIS_InteractiveObject;


public class AIS_MapIteratorOfMapOfInteractive extends jjAIS.TCollection_BasicMapIterator {

 static {
    System.loadLibrary("jjAIS");
 }
            
public AIS_MapIteratorOfMapOfInteractive() {
   AIS_MapIteratorOfMapOfInteractive_Create_1();
}

private final native void AIS_MapIteratorOfMapOfInteractive_Create_1();

public AIS_MapIteratorOfMapOfInteractive(AIS_MapOfInteractive aMap) {
   AIS_MapIteratorOfMapOfInteractive_Create_2(aMap);
}

private final native void AIS_MapIteratorOfMapOfInteractive_Create_2(AIS_MapOfInteractive aMap);

native public final void Initialize(AIS_MapOfInteractive aMap);
native public final AIS_InteractiveObject Key();


public native static void FinalizeValue(long anHID);

public void finalize() {
   synchronized(myCasLock) {
     if ( aVirer != 0 ) FinalizeValue(HID);
     HID = 0;
   }
}

}
