// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class AIS_DisplayMode extends jcas.Standard_Enumeration  {

public final static short AIS_WireFrame = 0;
public final static short AIS_Shaded = 1;
public final static short AIS_QuickHLR = 2;
public final static short AIS_ExactHLR = 3;


  
}
