// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;

import jjAIS.TCollection_BasicMapIterator;
import jjAIS.AIS_DataMapofIntegerListOfinteractive;
import jcas.Standard_Integer;
import jjAIS.AIS_ListOfInteractive;


public class AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive extends jjAIS.TCollection_BasicMapIterator {

 static {
    System.loadLibrary("jjAIS");
 }
            
public AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive() {
   AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive_Create_1();
}

private final native void AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive_Create_1();

public AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive(AIS_DataMapofIntegerListOfinteractive aMap) {
   AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive_Create_2(aMap);
}

private final native void AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive_Create_2(AIS_DataMapofIntegerListOfinteractive aMap);

native public final void Initialize(AIS_DataMapofIntegerListOfinteractive aMap);
native public final int Key();
native public final AIS_ListOfInteractive Value();


public native static void FinalizeValue(long anHID);

public void finalize() {
   synchronized(myCasLock) {
     if ( aVirer != 0 ) FinalizeValue(HID);
     HID = 0;
   }
}

}
