// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;

import jjAIS.TCollection_BasicMap;
import jcas.Standard_Integer;
import jcas.Standard_Boolean;
import jjAIS.AIS_InteractiveObject;
import jjAIS.AIS_GlobalStatus;


public class AIS_DataMapOfIOStatus extends jjAIS.TCollection_BasicMap {

 static {
    System.loadLibrary("jjAIS");
 }
            
public AIS_DataMapOfIOStatus(int NbBuckets) {
   AIS_DataMapOfIOStatus_Create_1(NbBuckets);
}

private final native void AIS_DataMapOfIOStatus_Create_1(int NbBuckets);

native public final AIS_DataMapOfIOStatus Assign(AIS_DataMapOfIOStatus Other);
native public final void ReSize(int NbBuckets);
native public final void Clear();
native public final boolean Bind(AIS_InteractiveObject K,AIS_GlobalStatus I);
native public final boolean IsBound(AIS_InteractiveObject K);
native public final boolean UnBind(AIS_InteractiveObject K);
native public final AIS_GlobalStatus Find(AIS_InteractiveObject K);
native public final AIS_GlobalStatus ChangeFind(AIS_InteractiveObject K);
public AIS_DataMapOfIOStatus() {
}



public native static void FinalizeValue(long anHID);

public void finalize() {
   synchronized(myCasLock) {
     if ( aVirer != 0 ) FinalizeValue(HID);
     HID = 0;
   }
}

}
