// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class AIS_KindOfInteractive extends jcas.Standard_Enumeration  {

public final static short AIS_KOI_None = 0;
public final static short AIS_KOI_Datum = 1;
public final static short AIS_KOI_Shape = 2;
public final static short AIS_KOI_Object = 3;
public final static short AIS_KOI_Relation = 4;


  
}
