// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class AIS_TypeOfIso extends jcas.Standard_Enumeration  {

public final static short AIS_TOI_IsoU = 0;
public final static short AIS_TOI_IsoV = 1;
public final static short AIS_TOI_Both = 2;


  
}
