// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class AIS_StatusOfDetection extends jcas.Standard_Enumeration  {

public final static short AIS_SOD_Error = 0;
public final static short AIS_SOD_Nothing = 1;
public final static short AIS_SOD_AllBad = 2;
public final static short AIS_SOD_Selected = 3;
public final static short AIS_SOD_OnlyOneDetected = 4;
public final static short AIS_SOD_OnlyOneGood = 5;
public final static short AIS_SOD_SeveralGood = 6;


  
}
