// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;

import jjAIS.AIS_ListOfInteractive;
import jcas.Standard_Boolean;
import jjAIS.AIS_InteractiveObject;


public class AIS_ListIteratorOfListOfInteractive extends jcas.Object {

 static {
    System.loadLibrary("jjAIS");
 }
            
public AIS_ListIteratorOfListOfInteractive() {
   AIS_ListIteratorOfListOfInteractive_Create_1();
}

private final native void AIS_ListIteratorOfListOfInteractive_Create_1();

public AIS_ListIteratorOfListOfInteractive(AIS_ListOfInteractive L) {
   AIS_ListIteratorOfListOfInteractive_Create_2(L);
}

private final native void AIS_ListIteratorOfListOfInteractive_Create_2(AIS_ListOfInteractive L);

native public final void Initialize(AIS_ListOfInteractive L);
native public final boolean More();
native public final void Next();
native public final AIS_InteractiveObject Value();


public native static void FinalizeValue(long anHID);

public void finalize() {
   synchronized(myCasLock) {
     if ( aVirer != 0 ) FinalizeValue(HID);
     HID = 0;
   }
}

}
