// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class AIS_KindOfDimension extends jcas.Standard_Enumeration  {

public final static short AIS_KOD_NONE = 0;
public final static short AIS_KOD_LENGTH = 1;
public final static short AIS_KOD_PLANEANGLE = 2;
public final static short AIS_KOD_SOLIDANGLE = 3;
public final static short AIS_KOD_AREA = 4;
public final static short AIS_KOD_VOLUME = 5;
public final static short AIS_KOD_MASS = 6;
public final static short AIS_KOD_TIME = 7;
public final static short AIS_KOD_RADIUS = 8;
public final static short AIS_KOD_DIAMETER = 9;
public final static short AIS_KOD_CHAMF2D = 10;
public final static short AIS_KOD_CHAMF3D = 11;
public final static short AIS_KOD_OFFSET = 12;
public final static short AIS_KOD_ELLIPSERADIUS = 13;


  
}
