// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;

import jjAIS.TCollection_BasicMap;
import jcas.Standard_Integer;
import jcas.Standard_Boolean;
import jjAIS.AIS_LocalContext;


public class AIS_DataMapOfILC extends jjAIS.TCollection_BasicMap {

 static {
    System.loadLibrary("jjAIS");
 }
            
public AIS_DataMapOfILC(int NbBuckets) {
   AIS_DataMapOfILC_Create_1(NbBuckets);
}

private final native void AIS_DataMapOfILC_Create_1(int NbBuckets);

native public final AIS_DataMapOfILC Assign(AIS_DataMapOfILC Other);
native public final void ReSize(int NbBuckets);
native public final void Clear();
native public final boolean Bind(int K,AIS_LocalContext I);
native public final boolean IsBound(int K);
native public final boolean UnBind(int K);
native public final AIS_LocalContext Find(int K);
native public final AIS_LocalContext ChangeFind(int K);
public AIS_DataMapOfILC() {
}



public native static void FinalizeValue(long anHID);

public void finalize() {
   synchronized(myCasLock) {
     if ( aVirer != 0 ) FinalizeValue(HID);
     HID = 0;
   }
}

}
