// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class Aspect_TypeOfMarker extends jcas.Standard_Enumeration  {

public final static short Aspect_TOM_POINT = 0;
public final static short Aspect_TOM_PLUS = 1;
public final static short Aspect_TOM_STAR = 2;
public final static short Aspect_TOM_O = 3;
public final static short Aspect_TOM_X = 4;
public final static short Aspect_TOM_O_POINT = 5;
public final static short Aspect_TOM_O_PLUS = 6;
public final static short Aspect_TOM_O_STAR = 7;
public final static short Aspect_TOM_O_X = 8;
public final static short Aspect_TOM_BALL = 9;
public final static short Aspect_TOM_RING1 = 10;
public final static short Aspect_TOM_RING2 = 11;
public final static short Aspect_TOM_RING3 = 12;
public final static short Aspect_TOM_USERDEFINED = 13;


  
}
