// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class Aspect_TypeOfLine extends jcas.Standard_Enumeration  {

public final static short Aspect_TOL_SOLID = 0;
public final static short Aspect_TOL_DASH = 1;
public final static short Aspect_TOL_DOT = 2;
public final static short Aspect_TOL_DOTDASH = 3;
public final static short Aspect_TOL_USERDEFINED = 4;


  
}
