// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class DsgPrs_ArrowSide extends jcas.Standard_Enumeration  {

public final static short DsgPrs_AS_NONE = 0;
public final static short DsgPrs_AS_FIRSTAR = 1;
public final static short DsgPrs_AS_LASTAR = 2;
public final static short DsgPrs_AS_BOTHAR = 3;
public final static short DsgPrs_AS_FIRSTPT = 4;
public final static short DsgPrs_AS_LASTPT = 5;
public final static short DsgPrs_AS_BOTHPT = 6;
public final static short DsgPrs_AS_FIRSTAR_LASTPT = 7;
public final static short DsgPrs_AS_FIRSTPT_LASTAR = 8;


  
}
