// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class Graphic3d_NameOfMaterial extends jcas.Standard_Enumeration  {

public final static short Graphic3d_NOM_BRASS = 0;
public final static short Graphic3d_NOM_BRONZE = 1;
public final static short Graphic3d_NOM_COPPER = 2;
public final static short Graphic3d_NOM_GOLD = 3;
public final static short Graphic3d_NOM_PEWTER = 4;
public final static short Graphic3d_NOM_PLASTER = 5;
public final static short Graphic3d_NOM_PLASTIC = 6;
public final static short Graphic3d_NOM_SILVER = 7;
public final static short Graphic3d_NOM_STEEL = 8;
public final static short Graphic3d_NOM_STONE = 9;
public final static short Graphic3d_NOM_SHINY_PLASTIC = 10;
public final static short Graphic3d_NOM_SATIN = 11;
public final static short Graphic3d_NOM_METALIZED = 12;
public final static short Graphic3d_NOM_NEON_GNC = 13;
public final static short Graphic3d_NOM_CHROME = 14;
public final static short Graphic3d_NOM_ALUMINIUM = 15;
public final static short Graphic3d_NOM_OBSIDIAN = 16;
public final static short Graphic3d_NOM_NEON_PHC = 17;
public final static short Graphic3d_NOM_JADE = 18;
public final static short Graphic3d_NOM_DEFAULT = 19;
public final static short Graphic3d_NOM_UserDefined = 20;


  
}
