/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapOfIOStatus */

#ifndef _Included_jjAIS_AIS_DataMapOfIOStatus
#define _Included_jjAIS_AIS_DataMapOfIOStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    AIS_DataMapOfIOStatus_Create_1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_AIS_1DataMapOfIOStatus_1Create_11
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    Assign
 * Signature: (LjjAIS/AIS_DataMapOfIOStatus;)LjjAIS/AIS_DataMapOfIOStatus;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    ReSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_ReSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_Clear
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    Bind
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/AIS_GlobalStatus;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_Bind
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    IsBound
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_IsBound
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    UnBind
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_UnBind
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    Find
 * Signature: (LjjAIS/AIS_InteractiveObject;)LjjAIS/AIS_GlobalStatus;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_Find
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    ChangeFind
 * Signature: (LjjAIS/AIS_InteractiveObject;)LjjAIS/AIS_GlobalStatus;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_ChangeFind
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfIOStatus
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfIOStatus_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
