/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Aspect_TypeOfLine */

#ifndef _Included_jjAIS_Aspect_TypeOfLine
#define _Included_jjAIS_Aspect_TypeOfLine
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_Aspect_TypeOfLine_Aspect_TOL_SOLID
#define jjAIS_Aspect_TypeOfLine_Aspect_TOL_SOLID 0L
#undef jjAIS_Aspect_TypeOfLine_Aspect_TOL_DASH
#define jjAIS_Aspect_TypeOfLine_Aspect_TOL_DASH 1L
#undef jjAIS_Aspect_TypeOfLine_Aspect_TOL_DOT
#define jjAIS_Aspect_TypeOfLine_Aspect_TOL_DOT 2L
#undef jjAIS_Aspect_TypeOfLine_Aspect_TOL_DOTDASH
#define jjAIS_Aspect_TypeOfLine_Aspect_TOL_DOTDASH 3L
#undef jjAIS_Aspect_TypeOfLine_Aspect_TOL_USERDEFINED
#define jjAIS_Aspect_TypeOfLine_Aspect_TOL_USERDEFINED 4L
#ifdef __cplusplus
}
#endif
#endif
