/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_ConnectedShape */

#ifndef _Included_jjAIS_AIS_ConnectedShape
#define _Included_jjAIS_AIS_ConnectedShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    AIS_ConnectedShape_Create_1
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ConnectedShape_AIS_1ConnectedShape_1Create_11
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    AIS_ConnectedShape_Create_2
 * Signature: (LjjAIS/AIS_Shape;S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ConnectedShape_AIS_1ConnectedShape_1Create_12
  (JNIEnv *, jobject, jobject, jshort);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    AIS_ConnectedShape_Create_3
 * Signature: (LjjAIS/AIS_ConnectedShape;S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ConnectedShape_AIS_1ConnectedShape_1Create_13
  (JNIEnv *, jobject, jobject, jshort);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    Type
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1ConnectedShape_Type
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    Signature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1ConnectedShape_Signature
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    AcceptShapeDecomposition
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1ConnectedShape_AcceptShapeDecomposition
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    AIS_ConnectedShape_Connect_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ConnectedShape_AIS_1ConnectedShape_1Connect_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    AIS_ConnectedShape_Connect_2
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/TopLoc_Location;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ConnectedShape_AIS_1ConnectedShape_1Connect_12
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    AIS_ConnectedShape_Compute_3
 * Signature: (LjjAIS/PrsMgr_PresentationManager3d;LjjAIS/Prs3d_Presentation;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ConnectedShape_AIS_1ConnectedShape_1Compute_13
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    AIS_ConnectedShape_Compute_4
 * Signature: (LjjAIS/PrsMgr_PresentationManager2d;LjjAIS/Graphic2d_GraphicObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ConnectedShape_AIS_1ConnectedShape_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_ConnectedShape
 * Method:    Shape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1ConnectedShape_Shape
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
