/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TColStd_ListOfTransient */

#ifndef _Included_jjAIS_TColStd_ListOfTransient
#define _Included_jjAIS_TColStd_ListOfTransient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_TColStd_ListOfTransient
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_TColStd_1ListOfTransient_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
