/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_SelectMgr_ViewerSelector */

#ifndef _Included_jjAIS_SelectMgr_ViewerSelector
#define _Included_jjAIS_SelectMgr_ViewerSelector
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
