/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Standard_Storable */

#ifndef _Included_jjAIS_Standard_Storable
#define _Included_jjAIS_Standard_Storable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
