/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapNodeOfDataMapOfIOStatus */

#ifndef _Included_jjAIS_AIS_DataMapNodeOfDataMapOfIOStatus
#define _Included_jjAIS_AIS_DataMapNodeOfDataMapOfIOStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapNodeOfDataMapOfIOStatus
 * Method:    Key
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapNodeOfDataMapOfIOStatus_Key
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapNodeOfDataMapOfIOStatus
 * Method:    Value
 * Signature: ()LjjAIS/AIS_GlobalStatus;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapNodeOfDataMapOfIOStatus_Value
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
