/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_SelectMgr_IndexedMapOfOwner */

#ifndef _Included_jjAIS_SelectMgr_IndexedMapOfOwner
#define _Included_jjAIS_SelectMgr_IndexedMapOfOwner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_SelectMgr_IndexedMapOfOwner
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_SelectMgr_1IndexedMapOfOwner_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
