/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Geom_Geometry */

#ifndef _Included_jjAIS_Geom_Geometry
#define _Included_jjAIS_Geom_Geometry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
