/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TopoDS_Edge */

#ifndef _Included_jjAIS_TopoDS_Edge
#define _Included_jjAIS_TopoDS_Edge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_TopoDS_Edge
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_TopoDS_1Edge_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
