/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_PrsMgr_PresentationManager */

#ifndef _Included_jjAIS_PrsMgr_PresentationManager
#define _Included_jjAIS_PrsMgr_PresentationManager
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
