/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_gp_Trsf */

#ifndef _Included_jjAIS_gp_Trsf
#define _Included_jjAIS_gp_Trsf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_gp_Trsf
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_gp_1Trsf_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
