/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_TypeFilter */

#ifndef _Included_jjAIS_AIS_TypeFilter
#define _Included_jjAIS_AIS_TypeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_TypeFilter
 * Method:    AIS_TypeFilter_Create_0
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TypeFilter_AIS_1TypeFilter_1Create_10
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_TypeFilter
 * Method:    IsOk
 * Signature: (LjjAIS/SelectMgr_EntityOwner;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1TypeFilter_IsOk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
