/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_V3d_Viewer */

#ifndef _Included_jjAIS_V3d_Viewer
#define _Included_jjAIS_V3d_Viewer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
