// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat.h>
#include <AIS_DataMapIteratorOfDataMapOfSelStat.hxx>
#include <jcas.hxx>
#include <stdlib.h>
#include <Standard_ErrorHandler.hxx>
#include <Standard_Failure.hxx>
#include <Standard_SStream.hxx>

#include <AIS_DataMapOfSelStat.hxx>
#include <SelectMgr_SelectableObject.hxx>
#include <AIS_LocalStatus.hxx>


extern "C" {


JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_AIS_1DataMapIteratorOfDataMapOfSelStat_1Create_11 (JNIEnv *env, jobject theobj)
{

jcas_Locking alock(env);
{
try {
AIS_DataMapIteratorOfDataMapOfSelStat* theret = new AIS_DataMapIteratorOfDataMapOfSelStat();
jcas_SetHandle(env,theobj,theret);

}
catch (Standard_Failure) {
  Standard_SStream Err;
  Err <<   Standard_Failure::Caught(); 
  Err << (char) 0;
  jcas_ThrowException(env,GetSString(Err));
}
}
alock.Release();

}



JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_AIS_1DataMapIteratorOfDataMapOfSelStat_1Create_12 (JNIEnv *env, jobject theobj, jobject aMap)
{

jcas_Locking alock(env);
{
try {
AIS_DataMapOfSelStat* the_aMap = (AIS_DataMapOfSelStat*) jcas_GetHandle(env,aMap);
if ( the_aMap == NULL ) {

 // The following assumes availability of the default constructor (what may not
 // always be the case). Therefore explicit exception is thrown if the null
 // object has been passed.
 // the_aMap = new AIS_DataMapOfSelStat ();
 // jcas_SetHandle ( env, aMap, the_aMap );
 jcas_ThrowException (env, "NULL object has been passed while expecting an object manipulated by value");

}  // end if
AIS_DataMapIteratorOfDataMapOfSelStat* theret = new AIS_DataMapIteratorOfDataMapOfSelStat(*the_aMap);
jcas_SetHandle(env,theobj,theret);

}
catch (Standard_Failure) {
  Standard_SStream Err;
  Err <<   Standard_Failure::Caught(); 
  Err << (char) 0;
  jcas_ThrowException(env,GetSString(Err));
}
}
alock.Release();

}



JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_Initialize (JNIEnv *env, jobject theobj, jobject aMap)
{

jcas_Locking alock(env);
{
try {
AIS_DataMapOfSelStat* the_aMap = (AIS_DataMapOfSelStat*) jcas_GetHandle(env,aMap);
if ( the_aMap == NULL ) {

 // The following assumes availability of the default constructor (what may not
 // always be the case). Therefore explicit exception is thrown if the null
 // object has been passed.
 // the_aMap = new AIS_DataMapOfSelStat ();
 // jcas_SetHandle ( env, aMap, the_aMap );
 jcas_ThrowException (env, "NULL object has been passed while expecting an object manipulated by value");

}  // end if
AIS_DataMapIteratorOfDataMapOfSelStat* the_this = (AIS_DataMapIteratorOfDataMapOfSelStat*) jcas_GetHandle(env,theobj);
the_this->Initialize(*the_aMap);

}
catch (Standard_Failure) {
  Standard_SStream Err;
  Err <<   Standard_Failure::Caught(); 
  Err << (char) 0;
  jcas_ThrowException(env,GetSString(Err));
}
}
alock.Release();

}



JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_Key (JNIEnv *env, jobject theobj)
{
jobject thejret;

jcas_Locking alock(env);
{
try {
AIS_DataMapIteratorOfDataMapOfSelStat* the_this = (AIS_DataMapIteratorOfDataMapOfSelStat*) jcas_GetHandle(env,theobj);
Handle(SelectMgr_SelectableObject)* theret = new Handle(SelectMgr_SelectableObject);
*theret = the_this->Key();
thejret = jcas_CreateObject(env,"jjAIS/SelectMgr_SelectableObject",theret);

}
catch (Standard_Failure) {
  Standard_SStream Err;
  Err <<   Standard_Failure::Caught(); 
  Err << (char) 0;
  jcas_ThrowException(env,GetSString(Err));
}
}
alock.Release();
return thejret;
}



JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_Value (JNIEnv *env, jobject theobj)
{
jobject thejret;

jcas_Locking alock(env);
{
try {
AIS_DataMapIteratorOfDataMapOfSelStat* the_this = (AIS_DataMapIteratorOfDataMapOfSelStat*) jcas_GetHandle(env,theobj);
Handle(AIS_LocalStatus)* theret = new Handle(AIS_LocalStatus);
*theret = the_this->Value();
thejret = jcas_CreateObject(env,"jjAIS/AIS_LocalStatus",theret);

}
catch (Standard_Failure) {
  Standard_SStream Err;
  Err <<   Standard_Failure::Caught(); 
  Err << (char) 0;
  jcas_ThrowException(env,GetSString(Err));
}
}
alock.Release();
return thejret;
}



JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_FinalizeValue(JNIEnv *, jclass, jlong theid)
{
if (theid) {
  AIS_DataMapIteratorOfDataMapOfSelStat* theobj = (AIS_DataMapIteratorOfDataMapOfSelStat*) theid;
  delete theobj;
}
}


}
