/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_RadiusDimension */

#ifndef _Included_jjAIS_AIS_RadiusDimension
#define _Included_jjAIS_AIS_RadiusDimension
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_RadiusDimension
 * Method:    AIS_RadiusDimension_Create_1
 * Signature: (LjjAIS/TopoDS_Shape;DLjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1RadiusDimension_AIS_1RadiusDimension_1Create_11
  (JNIEnv *, jobject, jobject, jdouble, jobject);

/*
 * Class:     jjAIS_AIS_RadiusDimension
 * Method:    AIS_RadiusDimension_Create_2
 * Signature: (LjjAIS/TopoDS_Shape;DLjjAIS/TCollection_ExtendedString;LjjAIS/gp_Pnt;SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1RadiusDimension_AIS_1RadiusDimension_1Create_12
  (JNIEnv *, jobject, jobject, jdouble, jobject, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_RadiusDimension
 * Method:    SetFirstShape
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1RadiusDimension_SetFirstShape
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_RadiusDimension
 * Method:    KindOfDimension
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1RadiusDimension_KindOfDimension
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_RadiusDimension
 * Method:    IsMovable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1RadiusDimension_IsMovable
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_RadiusDimension
 * Method:    DrawFromCenter
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1RadiusDimension_DrawFromCenter
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_RadiusDimension
 * Method:    SetDrawFromCenter
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1RadiusDimension_SetDrawFromCenter
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_RadiusDimension
 * Method:    AIS_RadiusDimension_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1RadiusDimension_AIS_1RadiusDimension_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
