/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapNodeOfDataMapOfILC */

#ifndef _Included_jjAIS_AIS_DataMapNodeOfDataMapOfILC
#define _Included_jjAIS_AIS_DataMapNodeOfDataMapOfILC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapNodeOfDataMapOfILC
 * Method:    Key
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1DataMapNodeOfDataMapOfILC_Key
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapNodeOfDataMapOfILC
 * Method:    Value
 * Signature: ()LjjAIS/AIS_LocalContext;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapNodeOfDataMapOfILC_Value
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
