/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TCollection_ExtendedString */

#ifndef _Included_jjAIS_TCollection_ExtendedString
#define _Included_jjAIS_TCollection_ExtendedString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_TCollection_ExtendedString
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_TCollection_1ExtendedString_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
