/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive */

#ifndef _Included_jjAIS_AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive
#define _Included_jjAIS_AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive
 * Method:    AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapofIntegerListOfinteractive_AIS_1DataMapIteratorOfDataMapofIntegerListOfinteractive_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive
 * Method:    AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive_Create_2
 * Signature: (LjjAIS/AIS_DataMapofIntegerListOfinteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapofIntegerListOfinteractive_AIS_1DataMapIteratorOfDataMapofIntegerListOfinteractive_1Create_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive
 * Method:    Initialize
 * Signature: (LjjAIS/AIS_DataMapofIntegerListOfinteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapofIntegerListOfinteractive_Initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive
 * Method:    Key
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapofIntegerListOfinteractive_Key
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive
 * Method:    Value
 * Signature: ()LjjAIS/AIS_ListOfInteractive;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapofIntegerListOfinteractive_Value
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapofIntegerListOfinteractive
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapofIntegerListOfinteractive_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
