/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_MultipleConnectedInteractive */

#ifndef _Included_jjAIS_AIS_MultipleConnectedInteractive
#define _Included_jjAIS_AIS_MultipleConnectedInteractive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    AIS_MultipleConnectedInteractive_Create_0
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_AIS_1MultipleConnectedInteractive_1Create_10
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    Connect
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_Connect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    Type
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_Type
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    Signature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_Signature
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    HasConnection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_HasConnection
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    ConnectedTo
 * Signature: ()LjjAIS/AIS_SequenceOfInteractive;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_ConnectedTo
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    Disconnect
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_Disconnect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    DisconnectAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_DisconnectAll
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    AIS_MultipleConnectedInteractive_Compute_2
 * Signature: (LjjAIS/PrsMgr_PresentationManager2d;LjjAIS/Graphic2d_GraphicObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_AIS_1MultipleConnectedInteractive_1Compute_12
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    AIS_MultipleConnectedInteractive_Compute_3
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_AIS_1MultipleConnectedInteractive_1Compute_13
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_MultipleConnectedInteractive
 * Method:    AIS_MultipleConnectedInteractive_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MultipleConnectedInteractive_AIS_1MultipleConnectedInteractive_1Compute_14
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
