/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Prs3d_Drawer */

#ifndef _Included_jjAIS_Prs3d_Drawer
#define _Included_jjAIS_Prs3d_Drawer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    Prs3d_Drawer_Create_0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_Prs3d_1Drawer_1Create_10
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetTypeOfDeflection
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetTypeOfDeflection
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    TypeOfDeflection
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_Prs3d_1Drawer_TypeOfDeflection
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetMaximalChordialDeviation
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetMaximalChordialDeviation
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    MaximalChordialDeviation
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_Prs3d_1Drawer_MaximalChordialDeviation
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetDeviationCoefficient
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetDeviationCoefficient
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    DeviationCoefficient
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_Prs3d_1Drawer_DeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetHLRDeviationCoefficient
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetHLRDeviationCoefficient
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    HLRDeviationCoefficient
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_Prs3d_1Drawer_HLRDeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetHLRAngle
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetHLRAngle
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    HLRAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_Prs3d_1Drawer_HLRAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetDeviationAngle
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetDeviationAngle
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    DeviationAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_Prs3d_1Drawer_DeviationAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetDiscretisation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetDiscretisation
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    Discretisation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_Prs3d_1Drawer_Discretisation
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetMaximalParameterValue
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetMaximalParameterValue
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    MaximalParameterValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_Prs3d_1Drawer_MaximalParameterValue
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetIsoOnPlane
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetIsoOnPlane
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    IsoOnPlane
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_Prs3d_1Drawer_IsoOnPlane
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    UIsoAspect
 * Signature: ()LjjAIS/Prs3d_IsoAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_UIsoAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetUIsoAspect
 * Signature: (LjjAIS/Prs3d_IsoAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetUIsoAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    VIsoAspect
 * Signature: ()LjjAIS/Prs3d_IsoAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_VIsoAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetVIsoAspect
 * Signature: (LjjAIS/Prs3d_IsoAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetVIsoAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    FreeBoundaryAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_FreeBoundaryAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetFreeBoundaryAspect
 * Signature: (LjjAIS/Prs3d_LineAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetFreeBoundaryAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetFreeBoundaryDraw
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetFreeBoundaryDraw
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    FreeBoundaryDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_Prs3d_1Drawer_FreeBoundaryDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    WireAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_WireAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetWireAspect
 * Signature: (LjjAIS/Prs3d_LineAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetWireAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetWireDraw
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetWireDraw
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    WireDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_Prs3d_1Drawer_WireDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    UnFreeBoundaryAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_UnFreeBoundaryAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetUnFreeBoundaryAspect
 * Signature: (LjjAIS/Prs3d_LineAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetUnFreeBoundaryAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetUnFreeBoundaryDraw
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetUnFreeBoundaryDraw
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    UnFreeBoundaryDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_Prs3d_1Drawer_UnFreeBoundaryDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    LineAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_LineAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetLineAspect
 * Signature: (LjjAIS/Prs3d_LineAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetLineAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    TextAspect
 * Signature: ()LjjAIS/Prs3d_TextAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_TextAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetTextAspect
 * Signature: (LjjAIS/Prs3d_TextAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetTextAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetLineArrowDraw
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetLineArrowDraw
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    LineArrowDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_Prs3d_1Drawer_LineArrowDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    ArrowAspect
 * Signature: ()LjjAIS/Prs3d_ArrowAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_ArrowAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetArrowAspect
 * Signature: (LjjAIS/Prs3d_ArrowAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetArrowAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    PointAspect
 * Signature: ()LjjAIS/Prs3d_PointAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_PointAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetPointAspect
 * Signature: (LjjAIS/Prs3d_PointAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetPointAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    ShadingAspect
 * Signature: ()LjjAIS/Prs3d_ShadingAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_ShadingAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetShadingAspect
 * Signature: (LjjAIS/Prs3d_ShadingAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetShadingAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetShadingAspectGlobal
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetShadingAspectGlobal
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    ShadingAspectGlobal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_Prs3d_1Drawer_ShadingAspectGlobal
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    DrawHiddenLine
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_Prs3d_1Drawer_DrawHiddenLine
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    EnableDrawHiddenLine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_EnableDrawHiddenLine
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    DisableDrawHiddenLine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_DisableDrawHiddenLine
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    HiddenLineAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_HiddenLineAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetHiddenLineAspect
 * Signature: (LjjAIS/Prs3d_LineAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetHiddenLineAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SeenLineAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_SeenLineAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetSeenLineAspect
 * Signature: (LjjAIS/Prs3d_LineAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetSeenLineAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    PlaneAspect
 * Signature: ()LjjAIS/Prs3d_PlaneAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_PlaneAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetPlaneAspect
 * Signature: (LjjAIS/Prs3d_PlaneAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetPlaneAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    VectorAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_VectorAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetVectorAspect
 * Signature: (LjjAIS/Prs3d_LineAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetVectorAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    DatumAspect
 * Signature: ()LjjAIS/Prs3d_DatumAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_DatumAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetDatumAspect
 * Signature: (LjjAIS/Prs3d_DatumAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetDatumAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    LengthAspect
 * Signature: ()LjjAIS/Prs3d_LengthAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_LengthAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetLengthAspect
 * Signature: (LjjAIS/Prs3d_LengthAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetLengthAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    AngleAspect
 * Signature: ()LjjAIS/Prs3d_AngleAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_AngleAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetAngleAspect
 * Signature: (LjjAIS/Prs3d_AngleAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetAngleAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    RadiusAspect
 * Signature: ()LjjAIS/Prs3d_RadiusAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_RadiusAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetRadiusAspect
 * Signature: (LjjAIS/Prs3d_RadiusAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetRadiusAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SectionAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_Prs3d_1Drawer_SectionAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_Prs3d_Drawer
 * Method:    SetSectionAspect
 * Signature: (LjjAIS/Prs3d_LineAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Prs3d_1Drawer_SetSectionAspect
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
