/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_GraphicTool */

#ifndef _Included_jjAIS_AIS_GraphicTool
#define _Included_jjAIS_AIS_GraphicTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_GraphicTool
 * Method:    AIS_GraphicTool_GetLineColor_1
 * Signature: (LjjAIS/Prs3d_Drawer;S)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1GraphicTool_AIS_1GraphicTool_1GetLineColor_11
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     jjAIS_AIS_GraphicTool
 * Method:    AIS_GraphicTool_GetLineColor_2
 * Signature: (LjjAIS/Prs3d_Drawer;SLjjAIS/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1GraphicTool_AIS_1GraphicTool_1GetLineColor_12
  (JNIEnv *, jclass, jobject, jshort, jobject);

/*
 * Class:     jjAIS_AIS_GraphicTool
 * Method:    GetLineWidth
 * Signature: (LjjAIS/Prs3d_Drawer;S)D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1GraphicTool_GetLineWidth
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     jjAIS_AIS_GraphicTool
 * Method:    GetLineType
 * Signature: (LjjAIS/Prs3d_Drawer;S)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1GraphicTool_GetLineType
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     jjAIS_AIS_GraphicTool
 * Method:    GetLineAtt
 * Signature: (LjjAIS/Prs3d_Drawer;SLjcas/Standard_Short;Ljcas/Standard_Real;Ljcas/Standard_Short;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1GraphicTool_GetLineAtt
  (JNIEnv *, jclass, jobject, jshort, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_GraphicTool
 * Method:    AIS_GraphicTool_GetInteriorColor_1
 * Signature: (LjjAIS/Prs3d_Drawer;)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1GraphicTool_AIS_1GraphicTool_1GetInteriorColor_11
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jjAIS_AIS_GraphicTool
 * Method:    AIS_GraphicTool_GetInteriorColor_2
 * Signature: (LjjAIS/Prs3d_Drawer;LjjAIS/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1GraphicTool_AIS_1GraphicTool_1GetInteriorColor_12
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jjAIS_AIS_GraphicTool
 * Method:    GetMaterial
 * Signature: (LjjAIS/Prs3d_Drawer;)LjjAIS/Graphic3d_MaterialAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1GraphicTool_GetMaterial
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jjAIS_AIS_GraphicTool
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1GraphicTool_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
