/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DisplayStatus */

#ifndef _Included_jjAIS_AIS_DisplayStatus
#define _Included_jjAIS_AIS_DisplayStatus
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_AIS_DisplayStatus_AIS_DS_Displayed
#define jjAIS_AIS_DisplayStatus_AIS_DS_Displayed 0L
#undef jjAIS_AIS_DisplayStatus_AIS_DS_Erased
#define jjAIS_AIS_DisplayStatus_AIS_DS_Erased 1L
#undef jjAIS_AIS_DisplayStatus_AIS_DS_FullErased
#define jjAIS_AIS_DisplayStatus_AIS_DS_FullErased 2L
#undef jjAIS_AIS_DisplayStatus_AIS_DS_Temporary
#define jjAIS_AIS_DisplayStatus_AIS_DS_Temporary 3L
#undef jjAIS_AIS_DisplayStatus_AIS_DS_None
#define jjAIS_AIS_DisplayStatus_AIS_DS_None 4L
#ifdef __cplusplus
}
#endif
#endif
