/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_Relation */

#ifndef _Included_jjAIS_AIS_Relation
#define _Included_jjAIS_AIS_Relation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_Relation
 * Method:    AIS_Relation_SetColor_1
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_AIS_1Relation_1SetColor_11
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    AIS_Relation_SetColor_2
 * Signature: (LjjAIS/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_AIS_1Relation_1SetColor_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    UnsetColor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_UnsetColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    Type
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Relation_Type
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    KindOfDimension
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Relation_KindOfDimension
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    IsMovable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Relation_IsMovable
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    FirstShape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Relation_FirstShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetFirstShape
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetFirstShape
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SecondShape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Relation_SecondShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetSecondShape
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetSecondShape
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetBndBox
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetBndBox
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    UnsetBndBox
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_UnsetBndBox
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    Plane
 * Signature: ()LjjAIS/Geom_Plane;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Relation_Plane
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetPlane
 * Signature: (LjjAIS/Geom_Plane;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetPlane
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    Value
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Relation_Value
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetValue
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetValue
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    Position
 * Signature: ()LjjAIS/gp_Pnt;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Relation_Position
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetPosition
 * Signature: (LjjAIS/gp_Pnt;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetPosition
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    Text
 * Signature: ()LjjAIS/TCollection_ExtendedString;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Relation_Text
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetText
 * Signature: (LjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetText
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    ArrowSize
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Relation_ArrowSize
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetArrowSize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetArrowSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SymbolPrs
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Relation_SymbolPrs
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetSymbolPrs
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetSymbolPrs
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetExtShape
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetExtShape
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    ExtShape
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1Relation_ExtShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    AcceptDisplayMode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Relation_AcceptDisplayMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    SetAutomaticPosition
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Relation_SetAutomaticPosition
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_Relation
 * Method:    AutomaticPosition
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Relation_AutomaticPosition
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
