/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS */

#ifndef _Included_jjAIS_AIS
#define _Included_jjAIS_AIS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS
 * Method:    Nearest
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/gp_Pnt;)LjjAIS/gp_Pnt;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_Nearest
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    Farest
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/gp_Pnt;)LjjAIS/gp_Pnt;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_Farest
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    AIS_ComputeGeometry_1
 * Signature: (LjjAIS/TopoDS_Edge;LjjAIS/Geom_Curve;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_AIS_1ComputeGeometry_11
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    AIS_ComputeGeometry_2
 * Signature: (LjjAIS/TopoDS_Edge;LjjAIS/Geom_Curve;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/Geom_Curve;Ljcas/Standard_Boolean;Ljcas/Standard_Boolean;LjjAIS/Geom_Plane;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_AIS_1ComputeGeometry_12
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    AIS_ComputeGeometry_3
 * Signature: (LjjAIS/TopoDS_Edge;LjjAIS/TopoDS_Edge;LjjAIS/Geom_Curve;LjjAIS/Geom_Curve;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/Geom_Plane;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_AIS_1ComputeGeometry_13
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    AIS_ComputeGeometry_4
 * Signature: (LjjAIS/TopoDS_Edge;LjjAIS/TopoDS_Edge;Ljcas/Standard_Integer;LjjAIS/Geom_Curve;LjjAIS/Geom_Curve;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/Geom_Curve;Ljcas/Standard_Boolean;Ljcas/Standard_Boolean;LjjAIS/Geom_Plane;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_AIS_1ComputeGeometry_14
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    ComputeGeomCurve
 * Signature: (LjjAIS/Geom_Curve;DDLjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/Geom_Plane;Ljcas/Standard_Boolean;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_ComputeGeomCurve
  (JNIEnv *, jclass, jobject, jdouble, jdouble, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    AIS_ComputeGeometry_5
 * Signature: (LjjAIS/TopoDS_Vertex;LjjAIS/gp_Pnt;LjjAIS/Geom_Plane;Ljcas/Standard_Boolean;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_AIS_1ComputeGeometry_15
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    GetPlaneFromFace
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/gp_Pln;LjjAIS/Geom_Surface;Ljcas/Standard_Short;Ljcas/Standard_Real;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_GetPlaneFromFace
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    InitFaceLength
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/gp_Pln;LjjAIS/Geom_Surface;Ljcas/Standard_Short;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_InitFaceLength
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    ComputeLengthBetweenPlanarFaces
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/TopoDS_Face;LjjAIS/gp_Pln;LjjAIS/gp_Pln;Ljcas/Standard_Real;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Dir;ZLjjAIS/gp_Pnt;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_ComputeLengthBetweenPlanarFaces
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jboolean, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    ComputeLengthBetweenCurvilinearFaces
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/TopoDS_Face;LjjAIS/Geom_Surface;LjjAIS/Geom_Surface;ZLjcas/Standard_Real;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Dir;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_ComputeLengthBetweenCurvilinearFaces
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jboolean, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    ComputeAngleBetweenPlanarFaces
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/TopoDS_Face;LjjAIS/Geom_Surface;LjjAIS/gp_Ax1;DZLjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Dir;LjjAIS/gp_Dir;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_ComputeAngleBetweenPlanarFaces
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jdouble, jboolean, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    ComputeAngleBetweenCurvilinearFaces
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/TopoDS_Face;LjjAIS/Geom_Surface;LjjAIS/Geom_Surface;SSLjjAIS/gp_Ax1;DZLjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;LjjAIS/gp_Dir;LjjAIS/gp_Dir;LjjAIS/Geom_Plane;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_ComputeAngleBetweenCurvilinearFaces
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jshort, jshort, jobject, jdouble, jboolean, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    ProjectPointOnPlane
 * Signature: (LjjAIS/gp_Pnt;LjjAIS/gp_Pln;)LjjAIS/gp_Pnt;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_ProjectPointOnPlane
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    ProjectPointOnLine
 * Signature: (LjjAIS/gp_Pnt;LjjAIS/gp_Lin;)LjjAIS/gp_Pnt;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_ProjectPointOnLine
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    TranslatePointToBound
 * Signature: (LjjAIS/gp_Pnt;LjjAIS/gp_Dir;LjjAIS/Bnd_Box;)LjjAIS/gp_Pnt;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_TranslatePointToBound
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    InDomain
 * Signature: (DDD)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_InDomain
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     jjAIS_AIS
 * Method:    NearestApex
 * Signature: (LjjAIS/gp_Elips;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;DDLjcas/Standard_Boolean;)LjjAIS/gp_Pnt;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_NearestApex
  (JNIEnv *, jclass, jobject, jobject, jobject, jdouble, jdouble, jobject);

/*
 * Class:     jjAIS_AIS
 * Method:    DistanceFromApex
 * Signature: (LjjAIS/gp_Elips;LjjAIS/gp_Pnt;D)D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_DistanceFromApex
  (JNIEnv *, jclass, jobject, jobject, jdouble);

/*
 * Class:     jjAIS_AIS
 * Method:    ComputeProjEdgePresentation
 * Signature: (LjjAIS/Prs3d_Presentation;LjjAIS/AIS_Drawer;LjjAIS/TopoDS_Edge;LjjAIS/Geom_Curve;LjjAIS/gp_Pnt;LjjAIS/gp_Pnt;SDSS)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_ComputeProjEdgePresentation
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jshort, jdouble, jshort, jshort);

/*
 * Class:     jjAIS_AIS
 * Method:    ComputeProjVertexPresentation
 * Signature: (LjjAIS/Prs3d_Presentation;LjjAIS/AIS_Drawer;LjjAIS/TopoDS_Vertex;LjjAIS/gp_Pnt;SDSS)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_ComputeProjVertexPresentation
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jshort, jdouble, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
