/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_Line */

#ifndef _Included_jjAIS_AIS_Line
#define _Included_jjAIS_AIS_Line
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_Line
 * Method:    AIS_Line_Create_1
 * Signature: (LjjAIS/Geom_Line;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_AIS_1Line_1Create_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    AIS_Line_Create_2
 * Signature: (LjjAIS/Geom_Point;LjjAIS/Geom_Point;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_AIS_1Line_1Create_12
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    AIS_Line_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_AIS_1Line_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    Signature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1Line_Signature
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    Type
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Line_Type
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    Line
 * Signature: ()LjjAIS/Geom_Line;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Line_Line
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    Points
 * Signature: (LjjAIS/Geom_Point;LjjAIS/Geom_Point;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_Points
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    SetLine
 * Signature: (LjjAIS/Geom_Line;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_SetLine
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    SetPoints
 * Signature: (LjjAIS/Geom_Point;LjjAIS/Geom_Point;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_SetPoints
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    AIS_Line_SetColor_1
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_AIS_1Line_1SetColor_11
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    AIS_Line_SetColor_2
 * Signature: (LjjAIS/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_AIS_1Line_1SetColor_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    SetWidth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_SetWidth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    UnsetColor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_UnsetColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Line
 * Method:    UnsetWidth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Line_UnsetWidth
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
