/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_Drawer */

#ifndef _Included_jjAIS_AIS_Drawer
#define _Included_jjAIS_AIS_Drawer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_Create_0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1Create_10
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    TypeOfDeflection
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Drawer_TypeOfDeflection
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    MaximalChordialDeviation
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_MaximalChordialDeviation
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_SetDeviationCoefficient_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1SetDeviationCoefficient_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_SetHLRDeviationCoefficient_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1SetHLRDeviationCoefficient_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_SetDeviationAngle_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1SetDeviationAngle_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_SetHLRAngle_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1SetHLRAngle_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_SetDeviationCoefficient_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1SetDeviationCoefficient_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_SetHLRDeviationCoefficient_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1SetHLRDeviationCoefficient_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_SetDeviationAngle_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1SetDeviationAngle_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_SetHLRAngle_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1SetHLRAngle_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    DeviationCoefficient
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_DeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HLRDeviationCoefficient
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_HLRDeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    DeviationAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_DeviationAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HLRAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_HLRAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    PreviousDeviationCoefficient
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_PreviousDeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    PreviousHLRDeviationCoefficient
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_PreviousHLRDeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    PreviousDeviationAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_PreviousDeviationAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    PreviousHLRDeviationAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_PreviousHLRDeviationAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    IsOwnDeviationCoefficient
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_IsOwnDeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    IsOwnHLRDeviationCoefficient
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_IsOwnHLRDeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    IsOwnDeviationAngle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_IsOwnDeviationAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    IsOwnHLRDeviationAngle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_IsOwnHLRDeviationAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    Discretisation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1Drawer_Discretisation
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    MaximalParameterValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Drawer_MaximalParameterValue
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    IsoOnPlane
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_IsoOnPlane
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    UIsoAspect
 * Signature: ()LjjAIS/Prs3d_IsoAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_UIsoAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    VIsoAspect
 * Signature: ()LjjAIS/Prs3d_IsoAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_VIsoAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    FreeBoundaryAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_FreeBoundaryAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    FreeBoundaryDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_FreeBoundaryDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    WireAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_WireAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasLineAspect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasLineAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasWireAspect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasWireAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    WireDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_WireDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    UnFreeBoundaryAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_UnFreeBoundaryAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    UnFreeBoundaryDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_UnFreeBoundaryDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    LineAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_LineAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasTextAspect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasTextAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    TextAspect
 * Signature: ()LjjAIS/Prs3d_TextAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_TextAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    LineArrowDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_LineArrowDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    ArrowAspect
 * Signature: ()LjjAIS/Prs3d_ArrowAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_ArrowAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    PointAspect
 * Signature: ()LjjAIS/Prs3d_PointAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_PointAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasPointAspect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasPointAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    ShadingAspect
 * Signature: ()LjjAIS/Prs3d_ShadingAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_ShadingAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasShadingAspect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasShadingAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    ShadingAspectGlobal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_ShadingAspectGlobal
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    DrawHiddenLine
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_DrawHiddenLine
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HiddenLineAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_HiddenLineAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    SeenLineAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_SeenLineAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasPlaneAspect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasPlaneAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    PlaneAspect
 * Signature: ()LjjAIS/Prs3d_PlaneAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_PlaneAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    VectorAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_VectorAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasDatumAspect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasDatumAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    DatumAspect
 * Signature: ()LjjAIS/Prs3d_DatumAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_DatumAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    LengthAspect
 * Signature: ()LjjAIS/Prs3d_LengthAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_LengthAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasLengthAspect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasLengthAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AngleAspect
 * Signature: ()LjjAIS/Prs3d_AngleAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_AngleAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasAngleAspect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasAngleAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    RadiusAspect
 * Signature: ()LjjAIS/Prs3d_RadiusAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_RadiusAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    SectionAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_SectionAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_Link_1
 * Signature: ()LjjAIS/Prs3d_Drawer;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1Link_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasLink
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasLink
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    AIS_Drawer_Link_2
 * Signature: (LjjAIS/Prs3d_Drawer;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_AIS_1Drawer_1Link_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    ClearLocalAttributes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Drawer_ClearLocalAttributes
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    WasLastLocal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_WasLastLocal
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Drawer
 * Method:    HasLocalAttributes
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Drawer_HasLocalAttributes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
