/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Geom_Line */

#ifndef _Included_jjAIS_Geom_Line
#define _Included_jjAIS_Geom_Line
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
