/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_TexturedShape */

#ifndef _Included_jjAIS_AIS_TexturedShape
#define _Included_jjAIS_AIS_TexturedShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    AIS_TexturedShape_Create_0
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_AIS_1TexturedShape_1Create_10
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    SetTextureFileName
 * Signature: (LjjAIS/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_SetTextureFileName
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    SetTextureRepeat
 * Signature: (ZDD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_SetTextureRepeat
  (JNIEnv *, jobject, jboolean, jdouble, jdouble);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    SetTextureOrigin
 * Signature: (ZDD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_SetTextureOrigin
  (JNIEnv *, jobject, jboolean, jdouble, jdouble);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    SetTextureScale
 * Signature: (ZDD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_SetTextureScale
  (JNIEnv *, jobject, jboolean, jdouble, jdouble);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    AIS_TexturedShape_ShowTriangles_1
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_AIS_1TexturedShape_1ShowTriangles_11
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    SetTextureMapOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_SetTextureMapOn
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    SetTextureMapOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_SetTextureMapOff
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    EnableTextureModulate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_EnableTextureModulate
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    DisableTextureModulate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_DisableTextureModulate
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    UpdateAttributes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1TexturedShape_UpdateAttributes
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureMapState
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1TexturedShape_TextureMapState
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    URepeat
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1TexturedShape_URepeat
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureRepeat
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1TexturedShape_TextureRepeat
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    Deflection
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1TexturedShape_Deflection
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureFile
 * Signature: ()Ljcas/Standard_CString;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1TexturedShape_TextureFile
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    VRepeat
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1TexturedShape_VRepeat
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    AIS_TexturedShape_ShowTriangles_2
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1TexturedShape_AIS_1TexturedShape_1ShowTriangles_12
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureUOrigin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1TexturedShape_TextureUOrigin
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureVOrigin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1TexturedShape_TextureVOrigin
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureScaleU
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1TexturedShape_TextureScaleU
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureScaleV
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1TexturedShape_TextureScaleV
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureScale
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1TexturedShape_TextureScale
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureOrigin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1TexturedShape_TextureOrigin
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_TexturedShape
 * Method:    TextureModulate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1TexturedShape_TextureModulate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
