/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TCollection_BasicMapIterator */

#ifndef _Included_jjAIS_TCollection_BasicMapIterator
#define _Included_jjAIS_TCollection_BasicMapIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_TCollection_BasicMapIterator
 * Method:    Reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_TCollection_1BasicMapIterator_Reset
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_TCollection_BasicMapIterator
 * Method:    More
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_TCollection_1BasicMapIterator_More
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_TCollection_BasicMapIterator
 * Method:    Next
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_TCollection_1BasicMapIterator_Next
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_TCollection_BasicMapIterator
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_TCollection_1BasicMapIterator_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
