/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_ClearMode */

#ifndef _Included_jjAIS_AIS_ClearMode
#define _Included_jjAIS_AIS_ClearMode
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_AIS_ClearMode_AIS_CM_All
#define jjAIS_AIS_ClearMode_AIS_CM_All 0L
#undef jjAIS_AIS_ClearMode_AIS_CM_Interactive
#define jjAIS_AIS_ClearMode_AIS_CM_Interactive 1L
#undef jjAIS_AIS_ClearMode_AIS_CM_Filters
#define jjAIS_AIS_ClearMode_AIS_CM_Filters 2L
#undef jjAIS_AIS_ClearMode_AIS_CM_StandardModes
#define jjAIS_AIS_ClearMode_AIS_CM_StandardModes 3L
#undef jjAIS_AIS_ClearMode_AIS_CM_TemporaryShapePrs
#define jjAIS_AIS_ClearMode_AIS_CM_TemporaryShapePrs 4L
#ifdef __cplusplus
}
#endif
#endif
