/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TCollection_AsciiString */

#ifndef _Included_jjAIS_TCollection_AsciiString
#define _Included_jjAIS_TCollection_AsciiString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_TCollection_AsciiString
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_TCollection_1AsciiString_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
