/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_MaxRadiusDimension */

#ifndef _Included_jjAIS_AIS_MaxRadiusDimension
#define _Included_jjAIS_AIS_MaxRadiusDimension
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_MaxRadiusDimension
 * Method:    AIS_MaxRadiusDimension_Create_1
 * Signature: (LjjAIS/TopoDS_Shape;DLjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MaxRadiusDimension_AIS_1MaxRadiusDimension_1Create_11
  (JNIEnv *, jobject, jobject, jdouble, jobject);

/*
 * Class:     jjAIS_AIS_MaxRadiusDimension
 * Method:    AIS_MaxRadiusDimension_Create_2
 * Signature: (LjjAIS/TopoDS_Shape;DLjjAIS/TCollection_ExtendedString;LjjAIS/gp_Pnt;SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MaxRadiusDimension_AIS_1MaxRadiusDimension_1Create_12
  (JNIEnv *, jobject, jobject, jdouble, jobject, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_MaxRadiusDimension
 * Method:    AIS_MaxRadiusDimension_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MaxRadiusDimension_AIS_1MaxRadiusDimension_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
