/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Graphic3d_Structure */

#ifndef _Included_jjAIS_Graphic3d_Structure
#define _Included_jjAIS_Graphic3d_Structure
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
