// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <jjAIS_AIS_MapIteratorOfMapOfInteractive.h>
#include <AIS_MapIteratorOfMapOfInteractive.hxx>
#include <jcas.hxx>
#include <stdlib.h>
#include <Standard_ErrorHandler.hxx>
#include <Standard_Failure.hxx>
#include <Standard_SStream.hxx>

#include <AIS_MapOfInteractive.hxx>
#include <AIS_InteractiveObject.hxx>


extern "C" {


JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_AIS_1MapIteratorOfMapOfInteractive_1Create_11 (JNIEnv *env, jobject theobj)
{

jcas_Locking alock(env);
{
try {
AIS_MapIteratorOfMapOfInteractive* theret = new AIS_MapIteratorOfMapOfInteractive();
jcas_SetHandle(env,theobj,theret);

}
catch (Standard_Failure) {
  Standard_SStream Err;
  Err <<   Standard_Failure::Caught(); 
  Err << (char) 0;
  jcas_ThrowException(env,GetSString(Err));
}
}
alock.Release();

}



JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_AIS_1MapIteratorOfMapOfInteractive_1Create_12 (JNIEnv *env, jobject theobj, jobject aMap)
{

jcas_Locking alock(env);
{
try {
AIS_MapOfInteractive* the_aMap = (AIS_MapOfInteractive*) jcas_GetHandle(env,aMap);
if ( the_aMap == NULL ) {

 // The following assumes availability of the default constructor (what may not
 // always be the case). Therefore explicit exception is thrown if the null
 // object has been passed.
 // the_aMap = new AIS_MapOfInteractive ();
 // jcas_SetHandle ( env, aMap, the_aMap );
 jcas_ThrowException (env, "NULL object has been passed while expecting an object manipulated by value");

}  // end if
AIS_MapIteratorOfMapOfInteractive* theret = new AIS_MapIteratorOfMapOfInteractive(*the_aMap);
jcas_SetHandle(env,theobj,theret);

}
catch (Standard_Failure) {
  Standard_SStream Err;
  Err <<   Standard_Failure::Caught(); 
  Err << (char) 0;
  jcas_ThrowException(env,GetSString(Err));
}
}
alock.Release();

}



JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_Initialize (JNIEnv *env, jobject theobj, jobject aMap)
{

jcas_Locking alock(env);
{
try {
AIS_MapOfInteractive* the_aMap = (AIS_MapOfInteractive*) jcas_GetHandle(env,aMap);
if ( the_aMap == NULL ) {

 // The following assumes availability of the default constructor (what may not
 // always be the case). Therefore explicit exception is thrown if the null
 // object has been passed.
 // the_aMap = new AIS_MapOfInteractive ();
 // jcas_SetHandle ( env, aMap, the_aMap );
 jcas_ThrowException (env, "NULL object has been passed while expecting an object manipulated by value");

}  // end if
AIS_MapIteratorOfMapOfInteractive* the_this = (AIS_MapIteratorOfMapOfInteractive*) jcas_GetHandle(env,theobj);
the_this->Initialize(*the_aMap);

}
catch (Standard_Failure) {
  Standard_SStream Err;
  Err <<   Standard_Failure::Caught(); 
  Err << (char) 0;
  jcas_ThrowException(env,GetSString(Err));
}
}
alock.Release();

}



JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_Key (JNIEnv *env, jobject theobj)
{
jobject thejret;

jcas_Locking alock(env);
{
try {
AIS_MapIteratorOfMapOfInteractive* the_this = (AIS_MapIteratorOfMapOfInteractive*) jcas_GetHandle(env,theobj);
Handle(AIS_InteractiveObject)* theret = new Handle(AIS_InteractiveObject);
*theret = the_this->Key();
thejret = jcas_CreateObject(env,"jjAIS/AIS_InteractiveObject",theret);

}
catch (Standard_Failure) {
  Standard_SStream Err;
  Err <<   Standard_Failure::Caught(); 
  Err << (char) 0;
  jcas_ThrowException(env,GetSString(Err));
}
}
alock.Release();
return thejret;
}



JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_FinalizeValue(JNIEnv *, jclass, jlong theid)
{
if (theid) {
  AIS_MapIteratorOfMapOfInteractive* theobj = (AIS_MapIteratorOfMapOfInteractive*) theid;
  delete theobj;
}
}


}
