/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Quantity_Color */

#ifndef _Included_jjAIS_Quantity_Color
#define _Included_jjAIS_Quantity_Color
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_Quantity_Color
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_Quantity_1Color_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
