/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapOfSelStat */

#ifndef _Included_jjAIS_AIS_DataMapOfSelStat
#define _Included_jjAIS_AIS_DataMapOfSelStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    AIS_DataMapOfSelStat_Create_1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_AIS_1DataMapOfSelStat_1Create_11
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    Assign
 * Signature: (LjjAIS/AIS_DataMapOfSelStat;)LjjAIS/AIS_DataMapOfSelStat;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    ReSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_ReSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_Clear
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    Bind
 * Signature: (LjjAIS/SelectMgr_SelectableObject;LjjAIS/AIS_LocalStatus;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_Bind
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    IsBound
 * Signature: (LjjAIS/SelectMgr_SelectableObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_IsBound
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    UnBind
 * Signature: (LjjAIS/SelectMgr_SelectableObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_UnBind
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    Find
 * Signature: (LjjAIS/SelectMgr_SelectableObject;)LjjAIS/AIS_LocalStatus;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_Find
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    ChangeFind
 * Signature: (LjjAIS/SelectMgr_SelectableObject;)LjjAIS/AIS_LocalStatus;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_ChangeFind
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfSelStat
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfSelStat_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
