/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapNodeOfDataMapOfSelStat */

#ifndef _Included_jjAIS_AIS_DataMapNodeOfDataMapOfSelStat
#define _Included_jjAIS_AIS_DataMapNodeOfDataMapOfSelStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapNodeOfDataMapOfSelStat
 * Method:    Key
 * Signature: ()LjjAIS/SelectMgr_SelectableObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapNodeOfDataMapOfSelStat_Key
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapNodeOfDataMapOfSelStat
 * Method:    Value
 * Signature: ()LjjAIS/AIS_LocalStatus;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapNodeOfDataMapOfSelStat_Value
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
