/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_SequenceOfDimension */

#ifndef _Included_jjAIS_AIS_SequenceOfDimension
#define _Included_jjAIS_AIS_SequenceOfDimension
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_Clear
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    Assign
 * Signature: (LjjAIS/AIS_SequenceOfDimension;)LjjAIS/AIS_SequenceOfDimension;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1SequenceOfDimension_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_Append_1
 * Signature: (LjjAIS/AIS_Relation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1Append_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_Append_2
 * Signature: (LjjAIS/AIS_SequenceOfDimension;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1Append_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_Prepend_1
 * Signature: (LjjAIS/AIS_Relation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1Prepend_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_Prepend_2
 * Signature: (LjjAIS/AIS_SequenceOfDimension;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1Prepend_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_InsertBefore_1
 * Signature: (ILjjAIS/AIS_Relation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1InsertBefore_11
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_InsertBefore_2
 * Signature: (ILjjAIS/AIS_SequenceOfDimension;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1InsertBefore_12
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_InsertAfter_1
 * Signature: (ILjjAIS/AIS_Relation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1InsertAfter_11
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_InsertAfter_2
 * Signature: (ILjjAIS/AIS_SequenceOfDimension;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1InsertAfter_12
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    First
 * Signature: ()LjjAIS/AIS_Relation;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1SequenceOfDimension_First
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    Last
 * Signature: ()LjjAIS/AIS_Relation;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1SequenceOfDimension_Last
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    Split
 * Signature: (ILjjAIS/AIS_SequenceOfDimension;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_Split
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    Value
 * Signature: (I)LjjAIS/AIS_Relation;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1SequenceOfDimension_Value
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    SetValue
 * Signature: (ILjjAIS/AIS_Relation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_SetValue
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    ChangeValue
 * Signature: (I)LjjAIS/AIS_Relation;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1SequenceOfDimension_ChangeValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_Remove_1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1Remove_11
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    AIS_SequenceOfDimension_Remove_2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_AIS_1SequenceOfDimension_1Remove_12
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jjAIS_AIS_SequenceOfDimension
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SequenceOfDimension_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
