/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TCollection_MapNode */

#ifndef _Included_jjAIS_TCollection_MapNode
#define _Included_jjAIS_TCollection_MapNode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
