/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_PrsMgr_Presentations */

#ifndef _Included_jjAIS_PrsMgr_Presentations
#define _Included_jjAIS_PrsMgr_Presentations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_PrsMgr_Presentations
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_PrsMgr_1Presentations_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
