/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_OffsetDimension */

#ifndef _Included_jjAIS_AIS_OffsetDimension
#define _Included_jjAIS_AIS_OffsetDimension
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_OffsetDimension
 * Method:    AIS_OffsetDimension_Create_0
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/TopoDS_Shape;DLjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1OffsetDimension_AIS_1OffsetDimension_1Create_10
  (JNIEnv *, jobject, jobject, jobject, jdouble, jobject);

/*
 * Class:     jjAIS_AIS_OffsetDimension
 * Method:    AIS_OffsetDimension_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1OffsetDimension_AIS_1OffsetDimension_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_OffsetDimension
 * Method:    KindOfDimension
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1OffsetDimension_KindOfDimension
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_OffsetDimension
 * Method:    IsMovable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1OffsetDimension_IsMovable
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_OffsetDimension
 * Method:    SetRelativePos
 * Signature: (LjjAIS/gp_Trsf;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1OffsetDimension_SetRelativePos
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
