/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_SequenceNodeOfSequenceOfInteractive */

#ifndef _Included_jjAIS_AIS_SequenceNodeOfSequenceOfInteractive
#define _Included_jjAIS_AIS_SequenceNodeOfSequenceOfInteractive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_SequenceNodeOfSequenceOfInteractive
 * Method:    Value
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1SequenceNodeOfSequenceOfInteractive_Value
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
