/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_ParallelRelation */

#ifndef _Included_jjAIS_AIS_ParallelRelation
#define _Included_jjAIS_AIS_ParallelRelation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_ParallelRelation
 * Method:    AIS_ParallelRelation_Create_1
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/TopoDS_Shape;LjjAIS/Geom_Plane;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ParallelRelation_AIS_1ParallelRelation_1Create_11
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_ParallelRelation
 * Method:    AIS_ParallelRelation_Create_2
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/TopoDS_Shape;LjjAIS/Geom_Plane;LjjAIS/gp_Pnt;SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ParallelRelation_AIS_1ParallelRelation_1Create_12
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_ParallelRelation
 * Method:    IsMovable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1ParallelRelation_IsMovable
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_ParallelRelation
 * Method:    AIS_ParallelRelation_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ParallelRelation_AIS_1ParallelRelation_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
