/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_LocalContext */

#ifndef _Included_jjAIS_AIS_LocalContext
#define _Included_jjAIS_AIS_LocalContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_Create_2
 * Signature: (LjjAIS/AIS_InteractiveContext;IZZZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1Create_12
  (JNIEnv *, jobject, jobject, jint, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_AcceptErase_1
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1AcceptErase_11
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_AcceptErase_2
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1AcceptErase_12
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SetContext
 * Signature: (LjjAIS/AIS_InteractiveContext;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_SetContext
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SelectionName
 * Signature: ()LjjAIS/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_SelectionName
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    Terminate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_Terminate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    HasSameProjector
 * Signature: (LjjAIS/Select3D_Projector;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_HasSameProjector
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    Reactivate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_Reactivate
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    Display
 * Signature: (LjjAIS/AIS_InteractiveObject;IZI)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_Display
  (JNIEnv *, jobject, jobject, jint, jboolean, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    Load
 * Signature: (LjjAIS/AIS_InteractiveObject;ZI)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_Load
  (JNIEnv *, jobject, jobject, jboolean, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    Erase
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_Erase
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    Remove
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_Remove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    ClearPrs
 * Signature: (LjjAIS/AIS_InteractiveObject;I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_ClearPrs
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SetShapeDecomposition
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_SetShapeDecomposition
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    Clear
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_Clear
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    ActivateMode
 * Signature: (LjjAIS/AIS_InteractiveObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_ActivateMode
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DeactivateMode
 * Signature: (LjjAIS/AIS_InteractiveObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_DeactivateMode
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    Deactivate
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_Deactivate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    ActivateStandardMode
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_ActivateStandardMode
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DeactivateStandardMode
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_DeactivateStandardMode
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    StandardModes
 * Signature: ()LjjAIS/TColStd_ListOfInteger;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_StandardModes
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AddFilter
 * Signature: (LjjAIS/SelectMgr_Filter;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AddFilter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    RemoveFilter
 * Signature: (LjjAIS/SelectMgr_Filter;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_RemoveFilter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    ListOfFilter
 * Signature: ()LjjAIS/SelectMgr_ListOfFilter;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_ListOfFilter
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    Filter
 * Signature: ()LjjAIS/SelectMgr_OrFilter;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_Filter
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SetAutomaticHilight
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_SetAutomaticHilight
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AutomaticHilight
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_AutomaticHilight
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    MoveTo
 * Signature: (IILjjAIS/V3d_View;)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1LocalContext_MoveTo
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    HasNextDetected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_HasNextDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    HilightNextDetected
 * Signature: (LjjAIS/V3d_View;)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1LocalContext_HilightNextDetected
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    HilightPreviousDetected
 * Signature: (LjjAIS/V3d_View;)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1LocalContext_HilightPreviousDetected
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    UnhilightLastDetected
 * Signature: (LjjAIS/V3d_View;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_UnhilightLastDetected
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_Select_1
 * Signature: (Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1Select_11
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_ShiftSelect_1
 * Signature: (Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1ShiftSelect_11
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_Select_2
 * Signature: (IIIILjjAIS/V3d_View;Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1Select_12
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_ShiftSelect_2
 * Signature: (IIIILjjAIS/V3d_View;Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1ShiftSelect_12
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_Select_3
 * Signature: (LjjAIS/TColgp_Array1OfPnt2d;LjjAIS/V3d_View;Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1Select_13
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_ShiftSelect_3
 * Signature: (LjjAIS/TColgp_Array1OfPnt2d;LjjAIS/V3d_View;Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1ShiftSelect_13
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    HilightPicked
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_HilightPicked
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    UnhilightPicked
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_UnhilightPicked
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_UpdateSelected_1
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1UpdateSelected_11
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_UpdateSelected_2
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1UpdateSelected_12
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SetSelected
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_SetSelected
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_AddOrRemoveSelected_1
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1AddOrRemoveSelected_11
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_AddOrRemoveSelected_2
 * Signature: (LjjAIS/TopoDS_Shape;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1AddOrRemoveSelected_12
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_AddOrRemoveSelected_3
 * Signature: (LjjAIS/SelectMgr_EntityOwner;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1AddOrRemoveSelected_13
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    ClearSelected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_ClearSelected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    HasDetected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_HasDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    InitDetected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_InitDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    MoreDetected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_MoreDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    NextDetected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_NextDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DetectedCurrentShape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_DetectedCurrentShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DetectedCurrentObject
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_DetectedCurrentObject
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    HasDetectedShape
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_HasDetectedShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DetectedShape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_DetectedShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DetectedInteractive
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_DetectedInteractive
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DetectedOwner
 * Signature: ()LjjAIS/SelectMgr_EntityOwner;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_DetectedOwner
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    InitSelected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_InitSelected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    MoreSelected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_MoreSelected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    NextSelected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_NextSelected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    HasShape
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_HasShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SelectedShape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_SelectedShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SelectedOwner
 * Signature: ()LjjAIS/SelectMgr_EntityOwner;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_SelectedOwner
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_IsSelected_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1IsSelected_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_IsSelected_2
 * Signature: (LjjAIS/SelectMgr_EntityOwner;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1IsSelected_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SelectedInteractive
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_SelectedInteractive
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    HasApplicative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_HasApplicative
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SelectedApplicative
 * Signature: ()LjjAIS/Standard_Transient;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_SelectedApplicative
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SetDisplayPriority
 * Signature: (LjjAIS/AIS_InteractiveObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_SetDisplayPriority
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DisplayedObjects
 * Signature: (LjjAIS/TColStd_MapOfTransient;)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1LocalContext_DisplayedObjects
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    IsIn
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_IsIn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_IsDisplayed_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1IsDisplayed_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_IsDisplayed_2
 * Signature: (LjjAIS/AIS_InteractiveObject;I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1IsDisplayed_12
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SelectionModes
 * Signature: (LjjAIS/AIS_InteractiveObject;)LjjAIS/TColStd_ListOfInteger;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_SelectionModes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SubIntensityOn
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_SubIntensityOn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    SubIntensityOff
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_SubIntensityOff
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_Hilight_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1Hilight_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_Hilight_2
 * Signature: (LjjAIS/AIS_InteractiveObject;S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1Hilight_12
  (JNIEnv *, jobject, jobject, jshort);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_Unhilight_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1Unhilight_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_IsHilighted_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1IsHilighted_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_IsHilighted_2
 * Signature: (LjjAIS/AIS_InteractiveObject;Ljcas/Standard_Boolean;Ljcas/Standard_Short;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1IsHilighted_12
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_SetSensitivity_1
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1SetSensitivity_11
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    AIS_LocalContext_SetSensitivity_2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_AIS_1LocalContext_1SetSensitivity_12
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    BeginImmediateDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_BeginImmediateDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    ImmediateAdd
 * Signature: (LjjAIS/AIS_InteractiveObject;I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_ImmediateAdd
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    ImmediateRemove
 * Signature: (LjjAIS/AIS_InteractiveObject;I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_ImmediateRemove
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    EndImmediateDraw
 * Signature: (LjjAIS/V3d_View;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_EndImmediateDraw
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    IsImmediateModeOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalContext_IsImmediateModeOn
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    UpdateConversion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_UpdateConversion
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    UpdateSort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_UpdateSort
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    LoadContextObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_LoadContextObjects
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    UnloadContextObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_UnloadContextObjects
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DisplayAreas
 * Signature: (LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_DisplayAreas
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    ClearAreas
 * Signature: (LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_ClearAreas
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    DisplaySensitive
 * Signature: (LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_DisplaySensitive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    ClearSensitive
 * Signature: (LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalContext_ClearSensitive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    MainSelector
 * Signature: ()LjjAIS/StdSelect_ViewerSelector3d;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_MainSelector
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    FindSelectedOwnerFromIO
 * Signature: (LjjAIS/AIS_InteractiveObject;)LjjAIS/SelectMgr_EntityOwner;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_FindSelectedOwnerFromIO
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalContext
 * Method:    FindSelectedOwnerFromShape
 * Signature: (LjjAIS/TopoDS_Shape;)LjjAIS/SelectMgr_EntityOwner;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalContext_FindSelectedOwnerFromShape
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
