/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_InteractiveContext */

#ifndef _Included_jjAIS_AIS_InteractiveContext
#define _Included_jjAIS_AIS_InteractiveContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Create_1
 * Signature: (LjjAIS/V3d_Viewer;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Create_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Create_2
 * Signature: (LjjAIS/V3d_Viewer;LjjAIS/V3d_Viewer;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Create_12
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Delete
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    IsCollectorClosed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_IsCollectorClosed
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    CloseCollector
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_CloseCollector
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    OpenCollector
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_OpenCollector
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetAutoActivateSelection
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetAutoActivateSelection
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    GetAutoActivateSelection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_GetAutoActivateSelection
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Display_1
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Display_11
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Display_2
 * Signature: (LjjAIS/AIS_InteractiveObject;IIZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Display_12
  (JNIEnv *, jobject, jobject, jint, jint, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Load
 * Signature: (LjjAIS/AIS_InteractiveObject;IZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Load
  (JNIEnv *, jobject, jobject, jint, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Erase
 * Signature: (LjjAIS/AIS_InteractiveObject;ZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Erase
  (JNIEnv *, jobject, jobject, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    EraseMode
 * Signature: (LjjAIS/AIS_InteractiveObject;IZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_EraseMode
  (JNIEnv *, jobject, jobject, jint, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    EraseAll
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_EraseAll
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DisplayAll
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_DisplayAll
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DisplayFromCollector
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_DisplayFromCollector
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    EraseSelected
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_EraseSelected
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DisplaySelected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_DisplaySelected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    KeepTemporary
 * Signature: (LjjAIS/AIS_InteractiveObject;I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_KeepTemporary
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Clear
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Clear
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ClearPrs
 * Signature: (LjjAIS/AIS_InteractiveObject;IZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ClearPrs
  (JNIEnv *, jobject, jobject, jint, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Remove
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Remove
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    RemoveAll
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_RemoveAll
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Hilight
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Hilight
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HilightWithColor
 * Signature: (LjjAIS/AIS_InteractiveObject;SZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_HilightWithColor
  (JNIEnv *, jobject, jobject, jshort, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Unhilight
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Unhilight
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetDisplayPriority
 * Signature: (LjjAIS/AIS_InteractiveObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetDisplayPriority
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Redisplay_1
 * Signature: (LjjAIS/AIS_InteractiveObject;ZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Redisplay_11
  (JNIEnv *, jobject, jobject, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Redisplay_2
 * Signature: (SIZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Redisplay_12
  (JNIEnv *, jobject, jshort, jint, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    RecomputePrsOnly
 * Signature: (LjjAIS/AIS_InteractiveObject;ZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_RecomputePrsOnly
  (JNIEnv *, jobject, jobject, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    RecomputeSelectionOnly
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_RecomputeSelectionOnly
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Update
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Update
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetDisplayMode_1
 * Signature: (LjjAIS/AIS_InteractiveObject;IZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetDisplayMode_11
  (JNIEnv *, jobject, jobject, jint, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UnsetDisplayMode
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UnsetDisplayMode
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetSelectionMode
 * Signature: (LjjAIS/AIS_InteractiveObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetSelectionMode
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UnsetSelectionMode
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UnsetSelectionMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetSensitivity_1
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetSensitivity_11
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetSensitivity_2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetSensitivity_12
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetLocation
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/TopLoc_Location;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetLocation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ResetLocation
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ResetLocation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HasLocation
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_HasLocation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Location
 * Signature: (LjjAIS/AIS_InteractiveObject;)LjjAIS/TopLoc_Location;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_Location
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetCurrentFacingModel
 * Signature: (LjjAIS/AIS_InteractiveObject;S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetCurrentFacingModel
  (JNIEnv *, jobject, jobject, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetColor_1
 * Signature: (LjjAIS/AIS_InteractiveObject;SZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetColor_11
  (JNIEnv *, jobject, jobject, jshort, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetColor_2
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/Quantity_Color;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetColor_12
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UnsetColor
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UnsetColor
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetWidth
 * Signature: (LjjAIS/AIS_InteractiveObject;DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetWidth
  (JNIEnv *, jobject, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UnsetWidth
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UnsetWidth
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetMaterial
 * Signature: (LjjAIS/AIS_InteractiveObject;SZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetMaterial
  (JNIEnv *, jobject, jobject, jshort, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UnsetMaterial
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UnsetMaterial
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetTransparency
 * Signature: (LjjAIS/AIS_InteractiveObject;DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetTransparency
  (JNIEnv *, jobject, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UnsetTransparency
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UnsetTransparency
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetDegenerateModel_1
 * Signature: (LjjAIS/AIS_InteractiveObject;SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetDegenerateModel_11
  (JNIEnv *, jobject, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetDegenerateModel_2
 * Signature: (SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetDegenerateModel_12
  (JNIEnv *, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetLocalAttributes
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/AIS_Drawer;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetLocalAttributes
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UnsetLocalAttributes
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UnsetLocalAttributes
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetPolygonOffsets
 * Signature: (LjjAIS/AIS_InteractiveObject;IDDZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetPolygonOffsets
  (JNIEnv *, jobject, jobject, jint, jdouble, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HasPolygonOffsets
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_HasPolygonOffsets
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    PolygonOffsets
 * Signature: (LjjAIS/AIS_InteractiveObject;Ljcas/Standard_Integer;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_PolygonOffsets
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetTrihedronSize
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetTrihedronSize
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    TrihedronSize
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1InteractiveContext_TrihedronSize
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetPlaneSize_1
 * Signature: (DDZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetPlaneSize_11
  (JNIEnv *, jobject, jdouble, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetPlaneSize_2
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetPlaneSize_12
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    PlaneSize
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_PlaneSize
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DisplayStatus
 * Signature: (LjjAIS/AIS_InteractiveObject;)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_DisplayStatus
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DisplayedModes
 * Signature: (LjjAIS/AIS_InteractiveObject;)LjjAIS/TColStd_ListOfInteger;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_DisplayedModes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_IsDisplayed_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1IsDisplayed_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_IsDisplayed_2
 * Signature: (LjjAIS/AIS_InteractiveObject;I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1IsDisplayed_12
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_IsHilighted_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1IsHilighted_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_IsHilighted_2
 * Signature: (LjjAIS/AIS_InteractiveObject;Ljcas/Standard_Boolean;Ljcas/Standard_Short;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1IsHilighted_12
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    IsInCollector
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_IsInCollector
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DisplayPriority
 * Signature: (LjjAIS/AIS_InteractiveObject;)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_DisplayPriority
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HasColor
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_HasColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Color_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Color_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Color_2
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Color_12
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Width
 * Signature: (LjjAIS/AIS_InteractiveObject;)D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1InteractiveContext_Width
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Status
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Status
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UpdateCurrentViewer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UpdateCurrentViewer
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UpdateCollector
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UpdateCollector
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DisplayMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_DisplayMode
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HilightColor
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_HilightColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SelectionColor_1
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SelectionColor_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    PreSelectionColor
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_PreSelectionColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DefaultColor
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_DefaultColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SubIntensityColor
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_SubIntensityColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetHilightColor
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetHilightColor
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SelectionColor_2
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SelectionColor_12
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetPreselectionColor
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetPreselectionColor
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetSubIntensityColor
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetSubIntensityColor
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetDisplayMode_2
 * Signature: (SZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetDisplayMode_12
  (JNIEnv *, jobject, jshort, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetDeviationCoefficient_1
 * Signature: (LjjAIS/AIS_InteractiveObject;DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetDeviationCoefficient_11
  (JNIEnv *, jobject, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetDeviationAngle_1
 * Signature: (LjjAIS/AIS_InteractiveObject;DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetDeviationAngle_11
  (JNIEnv *, jobject, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetAngleAndDeviation
 * Signature: (LjjAIS/AIS_InteractiveObject;DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetAngleAndDeviation
  (JNIEnv *, jobject, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetHLRDeviationCoefficient_1
 * Signature: (LjjAIS/AIS_InteractiveObject;DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetHLRDeviationCoefficient_11
  (JNIEnv *, jobject, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetHLRDeviationAngle
 * Signature: (LjjAIS/AIS_InteractiveObject;DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetHLRDeviationAngle
  (JNIEnv *, jobject, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetHLRAngleAndDeviation_1
 * Signature: (LjjAIS/AIS_InteractiveObject;DZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetHLRAngleAndDeviation_11
  (JNIEnv *, jobject, jobject, jdouble, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetDeviationCoefficient_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetDeviationCoefficient_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DeviationCoefficient
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1InteractiveContext_DeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetDeviationAngle_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetDeviationAngle_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DeviationAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1InteractiveContext_DeviationAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetHLRDeviationCoefficient_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetHLRDeviationCoefficient_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HLRDeviationCoefficient
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1InteractiveContext_HLRDeviationCoefficient
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetHLRAngle
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetHLRAngle
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HLRAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1InteractiveContext_HLRAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SetHLRAngleAndDeviation_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SetHLRAngleAndDeviation_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HiddenLineAspect
 * Signature: ()LjjAIS/Prs3d_LineAspect;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_HiddenLineAspect
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetHiddenLineAspect
 * Signature: (LjjAIS/Prs3d_LineAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetHiddenLineAspect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DrawHiddenLine
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_DrawHiddenLine
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    EnableDrawHiddenLine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_EnableDrawHiddenLine
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DisableDrawHiddenLine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_DisableDrawHiddenLine
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetIsoNumber
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetIsoNumber
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    IsoNumber
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_IsoNumber
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_IsoOnPlane_1
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1IsoOnPlane_11
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_IsoOnPlane_2
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1IsoOnPlane_12
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetSelectedAspect
 * Signature: (LjjAIS/Prs3d_BasicAspect;ZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetSelectedAspect
  (JNIEnv *, jobject, jobject, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    MoveTo
 * Signature: (IILjjAIS/V3d_View;)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_MoveTo
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HasNextDetected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_HasNextDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HilightNextDetected
 * Signature: (LjjAIS/V3d_View;)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_HilightNextDetected
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HilightPreviousDetected
 * Signature: (LjjAIS/V3d_View;)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_HilightPreviousDetected
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Select_1
 * Signature: (IIIILjjAIS/V3d_View;Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Select_11
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Select_2
 * Signature: (LjjAIS/TColgp_Array1OfPnt2d;LjjAIS/V3d_View;Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Select_12
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Select_3
 * Signature: (Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Select_13
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_ShiftSelect_1
 * Signature: (Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1ShiftSelect_11
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_ShiftSelect_2
 * Signature: (LjjAIS/TColgp_Array1OfPnt2d;LjjAIS/V3d_View;Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1ShiftSelect_12
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_ShiftSelect_3
 * Signature: (IIIILjjAIS/V3d_View;Z)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1ShiftSelect_13
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetToHilightSelected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetToHilightSelected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ToHilightSelected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_ToHilightSelected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetCurrentObject
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetCurrentObject
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AddOrRemoveCurrentObject
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AddOrRemoveCurrentObject
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UpdateCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UpdateCurrent
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    WasCurrentTouched
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_WasCurrentTouched
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetOkCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetOkCurrent
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    IsCurrent
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_IsCurrent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    InitCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_InitCurrent
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    MoreCurrent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_MoreCurrent
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    NextCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_NextCurrent
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Current
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_Current
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    NbCurrents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_NbCurrents
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    FirstCurrentObject
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_FirstCurrentObject
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HilightCurrents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_HilightCurrents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UnhilightCurrents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UnhilightCurrents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ClearCurrents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ClearCurrents
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetSelected
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetSelected
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetSelectedCurrent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetSelectedCurrent
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UpdateSelected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UpdateSelected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_AddOrRemoveSelected_1
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1AddOrRemoveSelected_11
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HilightSelected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_HilightSelected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UnhilightSelected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UnhilightSelected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ClearSelected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ClearSelected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_AddOrRemoveSelected_2
 * Signature: (LjjAIS/TopoDS_Shape;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1AddOrRemoveSelected_12
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_AddOrRemoveSelected_3
 * Signature: (LjjAIS/SelectMgr_EntityOwner;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1AddOrRemoveSelected_13
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    IsSelected
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_IsSelected
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    InitSelected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_InitSelected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    MoreSelected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_MoreSelected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    NextSelected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_NextSelected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    NbSelected
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_NbSelected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HasSelectedShape
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_HasSelectedShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SelectedShape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_SelectedShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SelectedOwner
 * Signature: ()LjjAIS/SelectMgr_EntityOwner;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_SelectedOwner
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    EntityOwners
 * Signature: (LjjAIS/SelectMgr_IndexedMapOfOwner;LjjAIS/AIS_InteractiveObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_EntityOwners
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Interactive
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_Interactive
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SelectedInteractive
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_SelectedInteractive
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HasApplicative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_HasApplicative
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Applicative
 * Signature: ()LjjAIS/Standard_Transient;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_Applicative
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HasDetected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_HasDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HasDetectedShape
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_HasDetectedShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DetectedShape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_DetectedShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DetectedInteractive
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_DetectedInteractive
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DetectedOwner
 * Signature: ()LjjAIS/SelectMgr_EntityOwner;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_DetectedOwner
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    InitDetected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_InitDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    MoreDetected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_MoreDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    NextDetected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_NextDetected
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DetectedCurrentShape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_DetectedCurrentShape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DetectedCurrentObject
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_DetectedCurrentObject
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    OpenLocalContext
 * Signature: (ZZZZ)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_OpenLocalContext
  (JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    CloseLocalContext
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_CloseLocalContext
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    IndexOfCurrentLocal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_IndexOfCurrentLocal
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    CloseAllContexts
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_CloseAllContexts
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ResetOriginalState
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ResetOriginalState
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ClearLocalContext
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ClearLocalContext
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    UseDisplayedObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_UseDisplayedObjects
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    NotUseDisplayedObjects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_NotUseDisplayedObjects
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    BeginImmediateDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_BeginImmediateDraw
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ImmediateAdd
 * Signature: (LjjAIS/AIS_InteractiveObject;I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_ImmediateAdd
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ImmediateRemove
 * Signature: (LjjAIS/AIS_InteractiveObject;I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_ImmediateRemove
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_EndImmediateDraw_1
 * Signature: (LjjAIS/V3d_View;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1EndImmediateDraw_11
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_EndImmediateDraw_2
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1EndImmediateDraw_12
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    IsImmediateModeOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_IsImmediateModeOn
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Drag
 * Signature: (LjjAIS/V3d_View;LjjAIS/AIS_InteractiveObject;LjjAIS/Geom_Transformation;ZZZ)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Drag
  (JNIEnv *, jobject, jobject, jobject, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetAutomaticHilight
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetAutomaticHilight
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AutomaticHilight
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_AutomaticHilight
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetZDetection
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetZDetection
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ZDetection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_ZDetection
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Activate
 * Signature: (LjjAIS/AIS_InteractiveObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_Activate
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Deactivate_1
 * Signature: (LjjAIS/AIS_InteractiveObject;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Deactivate_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_Deactivate_2
 * Signature: (LjjAIS/AIS_InteractiveObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1Deactivate_12
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ActivatedModes
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/TColStd_ListOfInteger;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ActivatedModes
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetShapeDecomposition
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetShapeDecomposition
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SetTemporaryAttributes
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/Prs3d_Drawer;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_SetTemporaryAttributes
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SubIntensityOn_1
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SubIntensityOn_11
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SubIntensityOff_1
 * Signature: (LjjAIS/AIS_InteractiveObject;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SubIntensityOff_11
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SubIntensityOn_2
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SubIntensityOn_12
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_SubIntensityOff_2
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1SubIntensityOff_12
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AddFilter
 * Signature: (LjjAIS/SelectMgr_Filter;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AddFilter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    RemoveFilter
 * Signature: (LjjAIS/SelectMgr_Filter;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_RemoveFilter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    RemoveFilters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_RemoveFilters
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ActivateStandardMode
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ActivateStandardMode
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DeactivateStandardMode
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_DeactivateStandardMode
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ActivatedStandardModes
 * Signature: ()LjjAIS/TColStd_ListOfInteger;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_ActivatedStandardModes
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Filters
 * Signature: ()LjjAIS/SelectMgr_ListOfFilter;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_Filters
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DefaultDrawer
 * Signature: ()LjjAIS/Prs3d_Drawer;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_DefaultDrawer
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    CurrentViewer
 * Signature: ()LjjAIS/V3d_Viewer;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_CurrentViewer
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_DisplayedObjects_1
 * Signature: (LjjAIS/AIS_ListOfInteractive;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1DisplayedObjects_11
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_DisplayedObjects_2
 * Signature: (SILjjAIS/AIS_ListOfInteractive;Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1DisplayedObjects_12
  (JNIEnv *, jobject, jshort, jint, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    Collector
 * Signature: ()LjjAIS/V3d_Viewer;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_Collector
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_ObjectsInCollector_1
 * Signature: (LjjAIS/AIS_ListOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1ObjectsInCollector_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_ObjectsInCollector_2
 * Signature: (SILjjAIS/AIS_ListOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1ObjectsInCollector_12
  (JNIEnv *, jobject, jshort, jint, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_ErasedObjects_1
 * Signature: (LjjAIS/AIS_ListOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1ErasedObjects_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_ErasedObjects_2
 * Signature: (SILjjAIS/AIS_ListOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1ErasedObjects_12
  (JNIEnv *, jobject, jshort, jint, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_ObjectsByDisplayStatus_1
 * Signature: (SLjjAIS/AIS_ListOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1ObjectsByDisplayStatus_11
  (JNIEnv *, jobject, jshort, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_ObjectsByDisplayStatus_2
 * Signature: (SISLjjAIS/AIS_ListOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1ObjectsByDisplayStatus_12
  (JNIEnv *, jobject, jshort, jint, jshort, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ObjectsInside
 * Signature: (LjjAIS/AIS_ListOfInteractive;SI)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ObjectsInside
  (JNIEnv *, jobject, jobject, jshort, jint);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HasOpenedContext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_HasOpenedContext
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    CurrentName
 * Signature: ()LjjAIS/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_CurrentName
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SelectionName
 * Signature: ()LjjAIS/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_SelectionName
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DomainOfMainViewer
 * Signature: ()Ljcas/Standard_CString;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_DomainOfMainViewer
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    DomainOfCollector
 * Signature: ()Ljcas/Standard_CString;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_DomainOfCollector
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    LocalContext
 * Signature: ()LjjAIS/AIS_LocalContext;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_LocalContext
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    SelectionManager
 * Signature: ()LjjAIS/SelectMgr_SelectionManager;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_SelectionManager
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    MainPrsMgr
 * Signature: ()LjjAIS/PrsMgr_PresentationManager3d;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_MainPrsMgr
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    CollectorPrsMgr
 * Signature: ()LjjAIS/PrsMgr_PresentationManager3d;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_CollectorPrsMgr
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    MainSelector
 * Signature: ()LjjAIS/StdSelect_ViewerSelector3d;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_MainSelector
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    LocalSelector
 * Signature: ()LjjAIS/StdSelect_ViewerSelector3d;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_LocalSelector
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    CollectorSelector
 * Signature: ()LjjAIS/StdSelect_ViewerSelector3d;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1InteractiveContext_CollectorSelector
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    PurgeDisplay
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_PurgeDisplay
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    HighestIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1InteractiveContext_HighestIndex
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_DisplayActiveAreas_1
 * Signature: (LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1DisplayActiveAreas_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ClearActiveAreas
 * Signature: (LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ClearActiveAreas
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_DisplayActiveSensitive_1
 * Signature: (LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1DisplayActiveSensitive_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    ClearActiveSensitive
 * Signature: (LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_ClearActiveSensitive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_DisplayActiveSensitive_2
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1DisplayActiveSensitive_12
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    AIS_InteractiveContext_DisplayActiveAreas_2
 * Signature: (LjjAIS/AIS_InteractiveObject;LjjAIS/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1InteractiveContext_AIS_1InteractiveContext_1DisplayActiveAreas_12
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_InteractiveContext
 * Method:    IsInLocal
 * Signature: (LjjAIS/AIS_InteractiveObject;Ljcas/Standard_Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1InteractiveContext_IsInLocal
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
