/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_TypeOfPlane */

#ifndef _Included_jjAIS_AIS_TypeOfPlane
#define _Included_jjAIS_AIS_TypeOfPlane
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_AIS_TypeOfPlane_AIS_TOPL_Unknown
#define jjAIS_AIS_TypeOfPlane_AIS_TOPL_Unknown 0L
#undef jjAIS_AIS_TypeOfPlane_AIS_TOPL_XYPlane
#define jjAIS_AIS_TypeOfPlane_AIS_TOPL_XYPlane 1L
#undef jjAIS_AIS_TypeOfPlane_AIS_TOPL_XZPlane
#define jjAIS_AIS_TypeOfPlane_AIS_TOPL_XZPlane 2L
#undef jjAIS_AIS_TypeOfPlane_AIS_TOPL_YZPlane
#define jjAIS_AIS_TypeOfPlane_AIS_TOPL_YZPlane 3L
#ifdef __cplusplus
}
#endif
#endif
