/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_IndexedDataMapOfOwnerPrs */

#ifndef _Included_jjAIS_AIS_IndexedDataMapOfOwnerPrs
#define _Included_jjAIS_AIS_IndexedDataMapOfOwnerPrs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    AIS_IndexedDataMapOfOwnerPrs_Create_1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_AIS_1IndexedDataMapOfOwnerPrs_1Create_11
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    Assign
 * Signature: (LjjAIS/AIS_IndexedDataMapOfOwnerPrs;)LjjAIS/AIS_IndexedDataMapOfOwnerPrs;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    ReSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_ReSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_Clear
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    Add
 * Signature: (LjjAIS/SelectMgr_EntityOwner;LjjAIS/Prs3d_Presentation;)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_Add
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    Substitute
 * Signature: (ILjjAIS/SelectMgr_EntityOwner;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_Substitute
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    RemoveLast
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_RemoveLast
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    Contains
 * Signature: (LjjAIS/SelectMgr_EntityOwner;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_Contains
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    FindKey
 * Signature: (I)LjjAIS/SelectMgr_EntityOwner;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_FindKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    FindFromIndex
 * Signature: (I)LjjAIS/Prs3d_Presentation;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_FindFromIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    ChangeFromIndex
 * Signature: (I)LjjAIS/Prs3d_Presentation;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_ChangeFromIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    FindIndex
 * Signature: (LjjAIS/SelectMgr_EntityOwner;)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_FindIndex
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    FindFromKey
 * Signature: (LjjAIS/SelectMgr_EntityOwner;)LjjAIS/Prs3d_Presentation;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_FindFromKey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    ChangeFromKey
 * Signature: (LjjAIS/SelectMgr_EntityOwner;)LjjAIS/Prs3d_Presentation;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_ChangeFromKey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_IndexedDataMapOfOwnerPrs
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1IndexedDataMapOfOwnerPrs_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
