/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TCollection_BaseSequence */

#ifndef _Included_jjAIS_TCollection_BaseSequence
#define _Included_jjAIS_TCollection_BaseSequence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_TCollection_BaseSequence
 * Method:    IsEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_TCollection_1BaseSequence_IsEmpty
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_TCollection_BaseSequence
 * Method:    Length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_TCollection_1BaseSequence_Length
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_TCollection_BaseSequence
 * Method:    Reverse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_TCollection_1BaseSequence_Reverse
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_TCollection_BaseSequence
 * Method:    Exchange
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jjAIS_TCollection_1BaseSequence_Exchange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jjAIS_TCollection_BaseSequence
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_TCollection_1BaseSequence_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
