/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_PrsMgr_TypeOfPresentation3d */

#ifndef _Included_jjAIS_PrsMgr_TypeOfPresentation3d
#define _Included_jjAIS_PrsMgr_TypeOfPresentation3d
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_PrsMgr_TypeOfPresentation3d_PrsMgr_TOP_AllView
#define jjAIS_PrsMgr_TypeOfPresentation3d_PrsMgr_TOP_AllView 0L
#undef jjAIS_PrsMgr_TypeOfPresentation3d_PrsMgr_TOP_ProjectorDependant
#define jjAIS_PrsMgr_TypeOfPresentation3d_PrsMgr_TOP_ProjectorDependant 1L
#ifdef __cplusplus
}
#endif
#endif
