/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat */

#ifndef _Included_jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat
#define _Included_jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat
 * Method:    AIS_DataMapIteratorOfDataMapOfSelStat_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_AIS_1DataMapIteratorOfDataMapOfSelStat_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat
 * Method:    AIS_DataMapIteratorOfDataMapOfSelStat_Create_2
 * Signature: (LjjAIS/AIS_DataMapOfSelStat;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_AIS_1DataMapIteratorOfDataMapOfSelStat_1Create_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat
 * Method:    Initialize
 * Signature: (LjjAIS/AIS_DataMapOfSelStat;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_Initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat
 * Method:    Key
 * Signature: ()LjjAIS/SelectMgr_SelectableObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_Key
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat
 * Method:    Value
 * Signature: ()LjjAIS/AIS_LocalStatus;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_Value
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfSelStat
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfSelStat_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
