/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TCollection_SeqNode */

#ifndef _Included_jjAIS_TCollection_SeqNode
#define _Included_jjAIS_TCollection_SeqNode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
