/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_MapIteratorOfMapOfInteractive */

#ifndef _Included_jjAIS_AIS_MapIteratorOfMapOfInteractive
#define _Included_jjAIS_AIS_MapIteratorOfMapOfInteractive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_MapIteratorOfMapOfInteractive
 * Method:    AIS_MapIteratorOfMapOfInteractive_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_AIS_1MapIteratorOfMapOfInteractive_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_MapIteratorOfMapOfInteractive
 * Method:    AIS_MapIteratorOfMapOfInteractive_Create_2
 * Signature: (LjjAIS/AIS_MapOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_AIS_1MapIteratorOfMapOfInteractive_1Create_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_MapIteratorOfMapOfInteractive
 * Method:    Initialize
 * Signature: (LjjAIS/AIS_MapOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_Initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_MapIteratorOfMapOfInteractive
 * Method:    Key
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_Key
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_MapIteratorOfMapOfInteractive
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapIteratorOfMapOfInteractive_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
