/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_Chamf3dDimension */

#ifndef _Included_jjAIS_AIS_Chamf3dDimension
#define _Included_jjAIS_AIS_Chamf3dDimension
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_Chamf3dDimension
 * Method:    AIS_Chamf3dDimension_Create_1
 * Signature: (LjjAIS/TopoDS_Shape;DLjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Chamf3dDimension_AIS_1Chamf3dDimension_1Create_11
  (JNIEnv *, jobject, jobject, jdouble, jobject);

/*
 * Class:     jjAIS_AIS_Chamf3dDimension
 * Method:    AIS_Chamf3dDimension_Create_2
 * Signature: (LjjAIS/TopoDS_Shape;DLjjAIS/TCollection_ExtendedString;LjjAIS/gp_Pnt;SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Chamf3dDimension_AIS_1Chamf3dDimension_1Create_12
  (JNIEnv *, jobject, jobject, jdouble, jobject, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_Chamf3dDimension
 * Method:    KindOfDimension
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Chamf3dDimension_KindOfDimension
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Chamf3dDimension
 * Method:    IsMovable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Chamf3dDimension_IsMovable
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Chamf3dDimension
 * Method:    AIS_Chamf3dDimension_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Chamf3dDimension_AIS_1Chamf3dDimension_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
