/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_AngleDimension */

#ifndef _Included_jjAIS_AIS_AngleDimension
#define _Included_jjAIS_AIS_AngleDimension
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    AIS_AngleDimension_Create_1
 * Signature: (LjjAIS/TopoDS_Edge;LjjAIS/TopoDS_Edge;LjjAIS/Geom_Plane;DLjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_AIS_1AngleDimension_1Create_11
  (JNIEnv *, jobject, jobject, jobject, jobject, jdouble, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    AIS_AngleDimension_Create_2
 * Signature: (LjjAIS/TopoDS_Edge;LjjAIS/TopoDS_Edge;LjjAIS/Geom_Plane;DLjjAIS/TCollection_ExtendedString;LjjAIS/gp_Pnt;SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_AIS_1AngleDimension_1Create_12
  (JNIEnv *, jobject, jobject, jobject, jobject, jdouble, jobject, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    AIS_AngleDimension_Create_3
 * Signature: (LjjAIS/TopoDS_Face;DLjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_AIS_1AngleDimension_1Create_13
  (JNIEnv *, jobject, jobject, jdouble, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    AIS_AngleDimension_Create_4
 * Signature: (LjjAIS/TopoDS_Face;DLjjAIS/TCollection_ExtendedString;LjjAIS/gp_Pnt;SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_AIS_1AngleDimension_1Create_14
  (JNIEnv *, jobject, jobject, jdouble, jobject, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    AIS_AngleDimension_Create_5
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/TopoDS_Face;LjjAIS/gp_Ax1;DLjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_AIS_1AngleDimension_1Create_15
  (JNIEnv *, jobject, jobject, jobject, jobject, jdouble, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    AIS_AngleDimension_Create_6
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/TopoDS_Face;LjjAIS/gp_Ax1;DLjjAIS/TCollection_ExtendedString;LjjAIS/gp_Pnt;SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_AIS_1AngleDimension_1Create_16
  (JNIEnv *, jobject, jobject, jobject, jobject, jdouble, jobject, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    AIS_AngleDimension_Create_7
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/TopoDS_Face;DLjjAIS/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_AIS_1AngleDimension_1Create_17
  (JNIEnv *, jobject, jobject, jobject, jdouble, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    AIS_AngleDimension_Create_8
 * Signature: (LjjAIS/TopoDS_Face;LjjAIS/TopoDS_Face;DLjjAIS/TCollection_ExtendedString;LjjAIS/gp_Pnt;SD)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_AIS_1AngleDimension_1Create_18
  (JNIEnv *, jobject, jobject, jobject, jdouble, jobject, jobject, jshort, jdouble);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    Axis
 * Signature: ()LjjAIS/gp_Ax1;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1AngleDimension_Axis
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    SetAxis
 * Signature: (LjjAIS/gp_Ax1;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_SetAxis
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    SetConeFace
 * Signature: (LjjAIS/TopoDS_Face;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_SetConeFace
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    SetFirstShape
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_SetFirstShape
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    SetSecondShape
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_SetSecondShape
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    KindOfDimension
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1AngleDimension_KindOfDimension
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    IsMovable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1AngleDimension_IsMovable
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_AngleDimension
 * Method:    AIS_AngleDimension_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1AngleDimension_AIS_1AngleDimension_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
