/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_StatusOfPick */

#ifndef _Included_jjAIS_AIS_StatusOfPick
#define _Included_jjAIS_AIS_StatusOfPick
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_AIS_StatusOfPick_AIS_SOP_Error
#define jjAIS_AIS_StatusOfPick_AIS_SOP_Error 0L
#undef jjAIS_AIS_StatusOfPick_AIS_SOP_NothingSelected
#define jjAIS_AIS_StatusOfPick_AIS_SOP_NothingSelected 1L
#undef jjAIS_AIS_StatusOfPick_AIS_SOP_Removed
#define jjAIS_AIS_StatusOfPick_AIS_SOP_Removed 2L
#undef jjAIS_AIS_StatusOfPick_AIS_SOP_OneSelected
#define jjAIS_AIS_StatusOfPick_AIS_SOP_OneSelected 3L
#undef jjAIS_AIS_StatusOfPick_AIS_SOP_SeveralSelected
#define jjAIS_AIS_StatusOfPick_AIS_SOP_SeveralSelected 4L
#ifdef __cplusplus
}
#endif
#endif
