/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapIteratorOfDataMapOfIOStatus */

#ifndef _Included_jjAIS_AIS_DataMapIteratorOfDataMapOfIOStatus
#define _Included_jjAIS_AIS_DataMapIteratorOfDataMapOfIOStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfIOStatus
 * Method:    AIS_DataMapIteratorOfDataMapOfIOStatus_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfIOStatus_AIS_1DataMapIteratorOfDataMapOfIOStatus_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfIOStatus
 * Method:    AIS_DataMapIteratorOfDataMapOfIOStatus_Create_2
 * Signature: (LjjAIS/AIS_DataMapOfIOStatus;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfIOStatus_AIS_1DataMapIteratorOfDataMapOfIOStatus_1Create_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfIOStatus
 * Method:    Initialize
 * Signature: (LjjAIS/AIS_DataMapOfIOStatus;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfIOStatus_Initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfIOStatus
 * Method:    Key
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfIOStatus_Key
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfIOStatus
 * Method:    Value
 * Signature: ()LjjAIS/AIS_GlobalStatus;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfIOStatus_Value
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfIOStatus
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfIOStatus_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
