/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TopoDS_Face */

#ifndef _Included_jjAIS_TopoDS_Face
#define _Included_jjAIS_TopoDS_Face
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_TopoDS_Face
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_TopoDS_1Face_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
