/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_gp_Ax1 */

#ifndef _Included_jjAIS_gp_Ax1
#define _Included_jjAIS_gp_Ax1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_gp_Ax1
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_gp_1Ax1_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
