/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_Triangulation */

#ifndef _Included_jjAIS_AIS_Triangulation
#define _Included_jjAIS_AIS_Triangulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_Triangulation
 * Method:    AIS_Triangulation_Create_0
 * Signature: (LjjAIS/Poly_Triangulation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Triangulation_AIS_1Triangulation_1Create_10
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Triangulation
 * Method:    SetColors
 * Signature: (LjjAIS/TColStd_HArray1OfInteger;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Triangulation_SetColors
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Triangulation
 * Method:    GetColors
 * Signature: ()LjjAIS/TColStd_HArray1OfInteger;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Triangulation_GetColors
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Triangulation
 * Method:    SetTriangulation
 * Signature: (LjjAIS/Poly_Triangulation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Triangulation_SetTriangulation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Triangulation
 * Method:    GetTriangulation
 * Signature: ()LjjAIS/Poly_Triangulation;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Triangulation_GetTriangulation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
