/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_SelectBasics_EntityOwner */

#ifndef _Included_jjAIS_SelectBasics_EntityOwner
#define _Included_jjAIS_SelectBasics_EntityOwner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_SelectBasics_EntityOwner
 * Method:    Set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_SelectBasics_1EntityOwner_Set
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_SelectBasics_EntityOwner
 * Method:    Priority
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_SelectBasics_1EntityOwner_Priority
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_SelectBasics_EntityOwner
 * Method:    HasLocation
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_SelectBasics_1EntityOwner_HasLocation
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_SelectBasics_EntityOwner
 * Method:    SetLocation
 * Signature: (LjjAIS/TopLoc_Location;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_SelectBasics_1EntityOwner_SetLocation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_SelectBasics_EntityOwner
 * Method:    ResetLocation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_SelectBasics_1EntityOwner_ResetLocation
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_SelectBasics_EntityOwner
 * Method:    Location
 * Signature: ()LjjAIS/TopLoc_Location;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_SelectBasics_1EntityOwner_Location
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
