/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_TypeOfAxis */

#ifndef _Included_jjAIS_AIS_TypeOfAxis
#define _Included_jjAIS_AIS_TypeOfAxis
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_AIS_TypeOfAxis_AIS_TOAX_Unknown
#define jjAIS_AIS_TypeOfAxis_AIS_TOAX_Unknown 0L
#undef jjAIS_AIS_TypeOfAxis_AIS_TOAX_XAxis
#define jjAIS_AIS_TypeOfAxis_AIS_TOAX_XAxis 1L
#undef jjAIS_AIS_TypeOfAxis_AIS_TOAX_YAxis
#define jjAIS_AIS_TypeOfAxis_AIS_TOAX_YAxis 2L
#undef jjAIS_AIS_TypeOfAxis_AIS_TOAX_ZAxis
#define jjAIS_AIS_TypeOfAxis_AIS_TOAX_ZAxis 3L
#ifdef __cplusplus
}
#endif
#endif
