/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_FixRelation */

#ifndef _Included_jjAIS_AIS_FixRelation
#define _Included_jjAIS_AIS_FixRelation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_FixRelation
 * Method:    AIS_FixRelation_Create_1
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/Geom_Plane;LjjAIS/TopoDS_Wire;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1FixRelation_AIS_1FixRelation_1Create_11
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_FixRelation
 * Method:    AIS_FixRelation_Create_2
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/Geom_Plane;LjjAIS/TopoDS_Wire;LjjAIS/gp_Pnt;D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1FixRelation_AIS_1FixRelation_1Create_12
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_FixRelation
 * Method:    AIS_FixRelation_Create_3
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/Geom_Plane;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1FixRelation_AIS_1FixRelation_1Create_13
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_FixRelation
 * Method:    AIS_FixRelation_Create_4
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/Geom_Plane;LjjAIS/gp_Pnt;D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1FixRelation_AIS_1FixRelation_1Create_14
  (JNIEnv *, jobject, jobject, jobject, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_FixRelation
 * Method:    Wire
 * Signature: ()LjjAIS/TopoDS_Wire;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1FixRelation_Wire
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_FixRelation
 * Method:    SetWire
 * Signature: (LjjAIS/TopoDS_Wire;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1FixRelation_SetWire
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_FixRelation
 * Method:    IsMovable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1FixRelation_IsMovable
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_FixRelation
 * Method:    AIS_FixRelation_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1FixRelation_AIS_1FixRelation_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
