/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Prs3d_ArrowAspect */

#ifndef _Included_jjAIS_Prs3d_ArrowAspect
#define _Included_jjAIS_Prs3d_ArrowAspect
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
