/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_PrsMgr_PresentableObject */

#ifndef _Included_jjAIS_PrsMgr_PresentableObject
#define _Included_jjAIS_PrsMgr_PresentableObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    TypeOfPresentation3d
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_PrsMgr_1PresentableObject_TypeOfPresentation3d
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    GetTransformPersistencePoint
 * Signature: ()LjjAIS/gp_Pnt;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_PrsMgr_1PresentableObject_GetTransformPersistencePoint
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    SetTypeOfPresentation
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_PrsMgr_1PresentableObject_SetTypeOfPresentation
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    PrsMgr_PresentableObject_SetToUpdate_1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_PrsMgr_1PresentableObject_PrsMgr_1PresentableObject_1SetToUpdate_11
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    PrsMgr_PresentableObject_SetToUpdate_2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_PrsMgr_1PresentableObject_PrsMgr_1PresentableObject_1SetToUpdate_12
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    ToBeUpdated
 * Signature: (LjjAIS/TColStd_ListOfInteger;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_PrsMgr_1PresentableObject_ToBeUpdated
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    SetLocation
 * Signature: (LjjAIS/TopLoc_Location;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_PrsMgr_1PresentableObject_SetLocation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    HasLocation
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_PrsMgr_1PresentableObject_HasLocation
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    Location
 * Signature: ()LjjAIS/TopLoc_Location;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_PrsMgr_1PresentableObject_Location
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    ResetLocation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_PrsMgr_1PresentableObject_ResetLocation
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    PrsMgr_PresentableObject_UpdateLocation_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_PrsMgr_1PresentableObject_PrsMgr_1PresentableObject_1UpdateLocation_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_PrsMgr_PresentableObject
 * Method:    PrsMgr_PresentableObject_UpdateLocation_2
 * Signature: (LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_PrsMgr_1PresentableObject_PrsMgr_1PresentableObject_1UpdateLocation_12
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
