/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_StdMapNodeOfMapOfInteractive */

#ifndef _Included_jjAIS_AIS_StdMapNodeOfMapOfInteractive
#define _Included_jjAIS_AIS_StdMapNodeOfMapOfInteractive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_StdMapNodeOfMapOfInteractive
 * Method:    Key
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1StdMapNodeOfMapOfInteractive_Key
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
