/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapOfILC */

#ifndef _Included_jjAIS_AIS_DataMapOfILC
#define _Included_jjAIS_AIS_DataMapOfILC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    AIS_DataMapOfILC_Create_1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfILC_AIS_1DataMapOfILC_1Create_11
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    Assign
 * Signature: (LjjAIS/AIS_DataMapOfILC;)LjjAIS/AIS_DataMapOfILC;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapOfILC_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    ReSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfILC_ReSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfILC_Clear
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    Bind
 * Signature: (ILjjAIS/AIS_LocalContext;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1DataMapOfILC_Bind
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    IsBound
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1DataMapOfILC_IsBound
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    UnBind
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1DataMapOfILC_UnBind
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    Find
 * Signature: (I)LjjAIS/AIS_LocalContext;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapOfILC_Find
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    ChangeFind
 * Signature: (I)LjjAIS/AIS_LocalContext;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapOfILC_ChangeFind
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_DataMapOfILC
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapOfILC_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
