/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Geom_Axis2Placement */

#ifndef _Included_jjAIS_Geom_Axis2Placement
#define _Included_jjAIS_Geom_Axis2Placement
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
