/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_ListIteratorOfListOfInteractive */

#ifndef _Included_jjAIS_AIS_ListIteratorOfListOfInteractive
#define _Included_jjAIS_AIS_ListIteratorOfListOfInteractive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_ListIteratorOfListOfInteractive
 * Method:    AIS_ListIteratorOfListOfInteractive_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ListIteratorOfListOfInteractive_AIS_1ListIteratorOfListOfInteractive_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_ListIteratorOfListOfInteractive
 * Method:    AIS_ListIteratorOfListOfInteractive_Create_2
 * Signature: (LjjAIS/AIS_ListOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ListIteratorOfListOfInteractive_AIS_1ListIteratorOfListOfInteractive_1Create_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_ListIteratorOfListOfInteractive
 * Method:    Initialize
 * Signature: (LjjAIS/AIS_ListOfInteractive;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ListIteratorOfListOfInteractive_Initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_ListIteratorOfListOfInteractive
 * Method:    More
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1ListIteratorOfListOfInteractive_More
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_ListIteratorOfListOfInteractive
 * Method:    Next
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ListIteratorOfListOfInteractive_Next
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_ListIteratorOfListOfInteractive
 * Method:    Value
 * Signature: ()LjjAIS/AIS_InteractiveObject;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1ListIteratorOfListOfInteractive_Value
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_ListIteratorOfListOfInteractive
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1ListIteratorOfListOfInteractive_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
