/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_SelectMgr_Filter */

#ifndef _Included_jjAIS_SelectMgr_Filter
#define _Included_jjAIS_SelectMgr_Filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_SelectMgr_Filter
 * Method:    IsOk
 * Signature: (LjjAIS/SelectMgr_EntityOwner;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_SelectMgr_1Filter_IsOk
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_SelectMgr_Filter
 * Method:    ActsOn
 * Signature: (S)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_SelectMgr_1Filter_ActsOn
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
