/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_ConnectStatus */

#ifndef _Included_jjAIS_AIS_ConnectStatus
#define _Included_jjAIS_AIS_ConnectStatus
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_AIS_ConnectStatus_AIS_CS_None
#define jjAIS_AIS_ConnectStatus_AIS_CS_None 0L
#undef jjAIS_AIS_ConnectStatus_AIS_CS_Connection
#define jjAIS_AIS_ConnectStatus_AIS_CS_Connection 1L
#undef jjAIS_AIS_ConnectStatus_AIS_CS_Transform
#define jjAIS_AIS_ConnectStatus_AIS_CS_Transform 2L
#undef jjAIS_AIS_ConnectStatus_AIS_CS_Both
#define jjAIS_AIS_ConnectStatus_AIS_CS_Both 3L
#ifdef __cplusplus
}
#endif
#endif
