/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Graphic2d_GraphicObject */

#ifndef _Included_jjAIS_Graphic2d_GraphicObject
#define _Included_jjAIS_Graphic2d_GraphicObject
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
