/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapNodeOfDataMapofIntegerListOfinteractive */

#ifndef _Included_jjAIS_AIS_DataMapNodeOfDataMapofIntegerListOfinteractive
#define _Included_jjAIS_AIS_DataMapNodeOfDataMapofIntegerListOfinteractive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapNodeOfDataMapofIntegerListOfinteractive
 * Method:    Key
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1DataMapNodeOfDataMapofIntegerListOfinteractive_Key
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapNodeOfDataMapofIntegerListOfinteractive
 * Method:    Value
 * Signature: ()LjjAIS/AIS_ListOfInteractive;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapNodeOfDataMapofIntegerListOfinteractive_Value
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
