/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_KindOfInteractive */

#ifndef _Included_jjAIS_AIS_KindOfInteractive
#define _Included_jjAIS_AIS_KindOfInteractive
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_AIS_KindOfInteractive_AIS_KOI_None
#define jjAIS_AIS_KindOfInteractive_AIS_KOI_None 0L
#undef jjAIS_AIS_KindOfInteractive_AIS_KOI_Datum
#define jjAIS_AIS_KindOfInteractive_AIS_KOI_Datum 1L
#undef jjAIS_AIS_KindOfInteractive_AIS_KOI_Shape
#define jjAIS_AIS_KindOfInteractive_AIS_KOI_Shape 2L
#undef jjAIS_AIS_KindOfInteractive_AIS_KOI_Object
#define jjAIS_AIS_KindOfInteractive_AIS_KOI_Object 3L
#undef jjAIS_AIS_KindOfInteractive_AIS_KOI_Relation
#define jjAIS_AIS_KindOfInteractive_AIS_KOI_Relation 4L
#ifdef __cplusplus
}
#endif
#endif
