/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DataMapIteratorOfDataMapOfILC */

#ifndef _Included_jjAIS_AIS_DataMapIteratorOfDataMapOfILC
#define _Included_jjAIS_AIS_DataMapIteratorOfDataMapOfILC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfILC
 * Method:    AIS_DataMapIteratorOfDataMapOfILC_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfILC_AIS_1DataMapIteratorOfDataMapOfILC_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfILC
 * Method:    AIS_DataMapIteratorOfDataMapOfILC_Create_2
 * Signature: (LjjAIS/AIS_DataMapOfILC;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfILC_AIS_1DataMapIteratorOfDataMapOfILC_1Create_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfILC
 * Method:    Initialize
 * Signature: (LjjAIS/AIS_DataMapOfILC;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfILC_Initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfILC
 * Method:    Key
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfILC_Key
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfILC
 * Method:    Value
 * Signature: ()LjjAIS/AIS_LocalContext;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfILC_Value
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_DataMapIteratorOfDataMapOfILC
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DataMapIteratorOfDataMapOfILC_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
