/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_MapOfInteractive */

#ifndef _Included_jjAIS_AIS_MapOfInteractive
#define _Included_jjAIS_AIS_MapOfInteractive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_MapOfInteractive
 * Method:    AIS_MapOfInteractive_Create_1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapOfInteractive_AIS_1MapOfInteractive_1Create_11
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_MapOfInteractive
 * Method:    Assign
 * Signature: (LjjAIS/AIS_MapOfInteractive;)LjjAIS/AIS_MapOfInteractive;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1MapOfInteractive_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_MapOfInteractive
 * Method:    ReSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapOfInteractive_ReSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_MapOfInteractive
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapOfInteractive_Clear
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_MapOfInteractive
 * Method:    Add
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1MapOfInteractive_Add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_MapOfInteractive
 * Method:    Contains
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1MapOfInteractive_Contains
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_MapOfInteractive
 * Method:    Remove
 * Signature: (LjjAIS/AIS_InteractiveObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1MapOfInteractive_Remove
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_MapOfInteractive
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1MapOfInteractive_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
