/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_LocalStatus */

#ifndef _Included_jjAIS_AIS_LocalStatus
#define _Included_jjAIS_AIS_LocalStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    AIS_LocalStatus_Create_0
 * Signature: (ZZIIIZS)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_AIS_1LocalStatus_1Create_10
  (JNIEnv *, jobject, jboolean, jboolean, jint, jint, jint, jboolean, jshort);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    Decomposed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalStatus_Decomposed
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    IsTemporary
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalStatus_IsTemporary
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    DisplayMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1LocalStatus_DisplayMode
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SelectionModes
 * Signature: ()LjjAIS/TColStd_ListOfInteger;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalStatus_SelectionModes
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    IsActivated
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalStatus_IsActivated
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    HilightMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1LocalStatus_HilightMode
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    IsSubIntensityOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalStatus_IsSubIntensityOn
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    HilightColor
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1LocalStatus_HilightColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SetDecomposition
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_SetDecomposition
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SetTemporary
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_SetTemporary
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SetDisplayMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_SetDisplayMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SetFirstDisplay
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_SetFirstDisplay
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    IsFirstDisplay
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalStatus_IsFirstDisplay
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    AddSelectionMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_AddSelectionMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    RemoveSelectionMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_RemoveSelectionMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    ClearSelectionModes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_ClearSelectionModes
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    IsSelModeIn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1LocalStatus_IsSelModeIn
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SetHilightMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_SetHilightMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SetHilightColor
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_SetHilightColor
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SubIntensityOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_SubIntensityOn
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SubIntensityOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_SubIntensityOff
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    SetPreviousState
 * Signature: (LjjAIS/Standard_Transient;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1LocalStatus_SetPreviousState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_LocalStatus
 * Method:    PreviousState
 * Signature: ()LjjAIS/Standard_Transient;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1LocalStatus_PreviousState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
