/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Prs3d_Projector */

#ifndef _Included_jjAIS_Prs3d_Projector
#define _Included_jjAIS_Prs3d_Projector
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
