/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_IdenticRelation */

#ifndef _Included_jjAIS_AIS_IdenticRelation
#define _Included_jjAIS_AIS_IdenticRelation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_IdenticRelation
 * Method:    AIS_IdenticRelation_Create_0
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/TopoDS_Shape;LjjAIS/Geom_Plane;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1IdenticRelation_AIS_1IdenticRelation_1Create_10
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_IdenticRelation
 * Method:    IsMovable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1IdenticRelation_IsMovable
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_IdenticRelation
 * Method:    AIS_IdenticRelation_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1IdenticRelation_AIS_1IdenticRelation_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
