/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_Aspect_TypeOfFacingModel */

#ifndef _Included_jjAIS_Aspect_TypeOfFacingModel
#define _Included_jjAIS_Aspect_TypeOfFacingModel
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_Aspect_TypeOfFacingModel_Aspect_TOFM_BOTH_SIDE
#define jjAIS_Aspect_TypeOfFacingModel_Aspect_TOFM_BOTH_SIDE 0L
#undef jjAIS_Aspect_TypeOfFacingModel_Aspect_TOFM_BACK_SIDE
#define jjAIS_Aspect_TypeOfFacingModel_Aspect_TOFM_BACK_SIDE 1L
#undef jjAIS_Aspect_TypeOfFacingModel_Aspect_TOFM_FRONT_SIDE
#define jjAIS_Aspect_TypeOfFacingModel_Aspect_TOFM_FRONT_SIDE 2L
#ifdef __cplusplus
}
#endif
#endif
