/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_SelectMgr_SelectionManager */

#ifndef _Included_jjAIS_SelectMgr_SelectionManager
#define _Included_jjAIS_SelectMgr_SelectionManager
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
