/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TColStd_MapOfTransient */

#ifndef _Included_jjAIS_TColStd_MapOfTransient
#define _Included_jjAIS_TColStd_MapOfTransient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_TColStd_MapOfTransient
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jjAIS_TColStd_1MapOfTransient_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
