/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_TColStd_HArray1OfInteger */

#ifndef _Included_jjAIS_TColStd_HArray1OfInteger
#define _Included_jjAIS_TColStd_HArray1OfInteger
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
