/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_Trihedron */

#ifndef _Included_jjAIS_AIS_Trihedron
#define _Included_jjAIS_AIS_Trihedron
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    AIS_Trihedron_Create_0
 * Signature: (LjjAIS/Geom_Axis2Placement;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_AIS_1Trihedron_1Create_10
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    Component
 * Signature: ()LjjAIS/Geom_Axis2Placement;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Trihedron_Component
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    SetComponent
 * Signature: (LjjAIS/Geom_Axis2Placement;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_SetComponent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    HasOwnSize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Trihedron_HasOwnSize
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    SetSize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_SetSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    UnsetSize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_UnsetSize
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    Size
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Trihedron_Size
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    XAxis
 * Signature: ()LjjAIS/AIS_Axis;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Trihedron_XAxis
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    YAxis
 * Signature: ()LjjAIS/AIS_Axis;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Trihedron_YAxis
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    Axis
 * Signature: ()LjjAIS/AIS_Axis;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Trihedron_Axis
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    Position
 * Signature: ()LjjAIS/AIS_Point;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Trihedron_Position
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    XYPlane
 * Signature: ()LjjAIS/AIS_Plane;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Trihedron_XYPlane
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    XZPlane
 * Signature: ()LjjAIS/AIS_Plane;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Trihedron_XZPlane
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    YZPlane
 * Signature: ()LjjAIS/AIS_Plane;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Trihedron_YZPlane
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    SetContext
 * Signature: (LjjAIS/AIS_InteractiveContext;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_SetContext
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    AcceptDisplayMode
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Trihedron_AcceptDisplayMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    AIS_Trihedron_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_AIS_1Trihedron_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    Signature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1Trihedron_Signature
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    Type
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Trihedron_Type
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    AIS_Trihedron_SetColor_1
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_AIS_1Trihedron_1SetColor_11
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    AIS_Trihedron_SetColor_2
 * Signature: (LjjAIS/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_AIS_1Trihedron_1SetColor_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    SetTextColor
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_SetTextColor
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    HasTextColor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Trihedron_HasTextColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    TextColor
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Trihedron_TextColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    SetArrowColor
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_SetArrowColor
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    HasArrowColor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Trihedron_HasArrowColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    ArrowColor
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Trihedron_ArrowColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    ExtremityPoints
 * Signature: (LjjAIS/TColgp_Array1OfPnt;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_ExtremityPoints
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    UnsetColor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_UnsetColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Trihedron
 * Method:    UnsetWidth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Trihedron_UnsetWidth
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
