/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_DsgPrs_ArrowSide */

#ifndef _Included_jjAIS_DsgPrs_ArrowSide
#define _Included_jjAIS_DsgPrs_ArrowSide
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_NONE
#define jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_NONE 0L
#undef jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_FIRSTAR
#define jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_FIRSTAR 1L
#undef jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_LASTAR
#define jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_LASTAR 2L
#undef jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_BOTHAR
#define jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_BOTHAR 3L
#undef jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_FIRSTPT
#define jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_FIRSTPT 4L
#undef jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_LASTPT
#define jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_LASTPT 5L
#undef jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_BOTHPT
#define jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_BOTHPT 6L
#undef jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_FIRSTAR_LASTPT
#define jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_FIRSTAR_LASTPT 7L
#undef jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_FIRSTPT_LASTAR
#define jjAIS_DsgPrs_ArrowSide_DsgPrs_AS_FIRSTPT_LASTAR 8L
#ifdef __cplusplus
}
#endif
#endif
