/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_Shape */

#ifndef _Included_jjAIS_AIS_Shape
#define _Included_jjAIS_AIS_Shape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_Create_0
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1Create_10
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    Signature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1Shape_Signature
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    Type
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Shape_Type
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AcceptShapeDecomposition
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Shape_AcceptShapeDecomposition
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    Set
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_Set
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    Shape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Shape_Shape
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetOwnDeviationCoefficient_1
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetOwnDeviationCoefficient_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetOwnHLRDeviationCoefficient_1
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetOwnHLRDeviationCoefficient_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetOwnDeviationAngle_1
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetOwnDeviationAngle_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetOwnHLRDeviationAngle_1
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetOwnHLRDeviationAngle_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetOwnDeviationCoefficient_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetOwnDeviationCoefficient_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetOwnHLRDeviationCoefficient_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetOwnHLRDeviationCoefficient_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    SetAngleAndDeviation
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_SetAngleAndDeviation
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    UserAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Shape_UserAngle
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetOwnDeviationAngle_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetOwnDeviationAngle_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    SetHLRAngleAndDeviation
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_SetHLRAngleAndDeviation
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetOwnHLRDeviationAngle_2
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetOwnHLRDeviationAngle_12
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    OwnDeviationCoefficient
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Shape_OwnDeviationCoefficient
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    OwnHLRDeviationCoefficient
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Shape_OwnHLRDeviationCoefficient
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    OwnDeviationAngle
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Shape_OwnDeviationAngle
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    OwnHLRDeviationAngle
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1Shape_OwnHLRDeviationAngle
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetColor_1
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetColor_11
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetColor_2
 * Signature: (LjjAIS/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetColor_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    UnsetColor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_UnsetColor
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    SetWidth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_SetWidth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    UnsetWidth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_UnsetWidth
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetMaterial_1
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetMaterial_11
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_SetMaterial_2
 * Signature: (LjjAIS/Graphic3d_MaterialAspect;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1SetMaterial_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    UnsetMaterial
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_UnsetMaterial
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    SetTransparency
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_SetTransparency
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    UnsetTransparency
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_UnsetTransparency
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    BoundingBox
 * Signature: ()LjjAIS/Bnd_Box;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1Shape_BoundingBox
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_Color_1
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1Color_11
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    AIS_Shape_Color_2
 * Signature: (LjjAIS/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1Shape_AIS_1Shape_1Color_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    Material
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Shape_Material
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    Transparency
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Shape_Transparency
  (JNIEnv *, jobject);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    SelectionType
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_jjAIS_AIS_1Shape_SelectionType
  (JNIEnv *, jclass, jint);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    SelectionMode
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_jjAIS_AIS_1Shape_SelectionMode
  (JNIEnv *, jclass, jshort);

/*
 * Class:     jjAIS_AIS_Shape
 * Method:    GetDeflection
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/Prs3d_Drawer;)D
 */
JNIEXPORT jdouble JNICALL Java_jjAIS_AIS_1Shape_GetDeflection
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
