/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_PerpendicularRelation */

#ifndef _Included_jjAIS_AIS_PerpendicularRelation
#define _Included_jjAIS_AIS_PerpendicularRelation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_PerpendicularRelation
 * Method:    AIS_PerpendicularRelation_Create_1
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/TopoDS_Shape;LjjAIS/Geom_Plane;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1PerpendicularRelation_AIS_1PerpendicularRelation_1Create_11
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_PerpendicularRelation
 * Method:    AIS_PerpendicularRelation_Create_2
 * Signature: (LjjAIS/TopoDS_Shape;LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1PerpendicularRelation_AIS_1PerpendicularRelation_1Create_12
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jjAIS_AIS_PerpendicularRelation
 * Method:    AIS_PerpendicularRelation_Compute_4
 * Signature: (LjjAIS/Prs3d_Projector;LjjAIS/Geom_Transformation;LjjAIS/Prs3d_Presentation;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1PerpendicularRelation_AIS_1PerpendicularRelation_1Compute_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
