/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_SignatureFilter */

#ifndef _Included_jjAIS_AIS_SignatureFilter
#define _Included_jjAIS_AIS_SignatureFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_SignatureFilter
 * Method:    AIS_SignatureFilter_Create_0
 * Signature: (SI)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1SignatureFilter_AIS_1SignatureFilter_1Create_10
  (JNIEnv *, jobject, jshort, jint);

/*
 * Class:     jjAIS_AIS_SignatureFilter
 * Method:    IsOk
 * Signature: (LjjAIS/SelectMgr_EntityOwner;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1SignatureFilter_IsOk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
