/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_DimensionOwner */

#ifndef _Included_jjAIS_AIS_DimensionOwner
#define _Included_jjAIS_AIS_DimensionOwner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_DimensionOwner
 * Method:    AIS_DimensionOwner_Create_0
 * Signature: (LjjAIS/SelectMgr_SelectableObject;I)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DimensionOwner_AIS_1DimensionOwner_1Create_10
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jjAIS_AIS_DimensionOwner
 * Method:    SetShape
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1DimensionOwner_SetShape
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_DimensionOwner
 * Method:    FixedShape
 * Signature: ()LjjAIS/TopoDS_Shape;
 */
JNIEXPORT jobject JNICALL Java_jjAIS_AIS_1DimensionOwner_FixedShape
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
