/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_MMgt_TShared */

#ifndef _Included_jjAIS_MMgt_TShared
#define _Included_jjAIS_MMgt_TShared
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
