/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_C0RegularityFilter */

#ifndef _Included_jjAIS_AIS_C0RegularityFilter
#define _Included_jjAIS_AIS_C0RegularityFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jjAIS_AIS_C0RegularityFilter
 * Method:    AIS_C0RegularityFilter_Create_0
 * Signature: (LjjAIS/TopoDS_Shape;)V
 */
JNIEXPORT void JNICALL Java_jjAIS_AIS_1C0RegularityFilter_AIS_1C0RegularityFilter_1Create_10
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jjAIS_AIS_C0RegularityFilter
 * Method:    ActsOn
 * Signature: (S)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1C0RegularityFilter_ActsOn
  (JNIEnv *, jobject, jshort);

/*
 * Class:     jjAIS_AIS_C0RegularityFilter
 * Method:    IsOk
 * Signature: (LjjAIS/SelectMgr_EntityOwner;)Z
 */
JNIEXPORT jboolean JNICALL Java_jjAIS_AIS_1C0RegularityFilter_IsOk
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
