/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jjAIS_AIS_KindOfUnit */

#ifndef _Included_jjAIS_AIS_KindOfUnit
#define _Included_jjAIS_AIS_KindOfUnit
#ifdef __cplusplus
extern "C" {
#endif
#undef jjAIS_AIS_KindOfUnit_AIS_TOU_LENGTH
#define jjAIS_AIS_KindOfUnit_AIS_TOU_LENGTH 0L
#undef jjAIS_AIS_KindOfUnit_AIS_TOU_SURFACE
#define jjAIS_AIS_KindOfUnit_AIS_TOU_SURFACE 1L
#undef jjAIS_AIS_KindOfUnit_AIS_TOU_VOLUME
#define jjAIS_AIS_KindOfUnit_AIS_TOU_VOLUME 2L
#undef jjAIS_AIS_KindOfUnit_AIS_TOU_PLANE_ANGLE
#define jjAIS_AIS_KindOfUnit_AIS_TOU_PLANE_ANGLE 3L
#undef jjAIS_AIS_KindOfUnit_AIS_TOU_SOLID_ANGLE
#define jjAIS_AIS_KindOfUnit_AIS_TOU_SOLID_ANGLE 4L
#undef jjAIS_AIS_KindOfUnit_AIS_TOU_MASS
#define jjAIS_AIS_KindOfUnit_AIS_TOU_MASS 5L
#undef jjAIS_AIS_KindOfUnit_AIS_TOU_FORCE
#define jjAIS_AIS_KindOfUnit_AIS_TOU_FORCE 6L
#undef jjAIS_AIS_KindOfUnit_AIS_TOU_TIME
#define jjAIS_AIS_KindOfUnit_AIS_TOU_TIME 7L
#ifdef __cplusplus
}
#endif
#endif
