// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;


public class PrsMgr_TypeOfPresentation3d extends jcas.Standard_Enumeration  {

public final static short PrsMgr_TOP_AllView = 0;
public final static short PrsMgr_TOP_ProjectorDependant = 1;


  
}
