// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;

import jcas.Object;

public class Standard_Storable extends jcas.Object {

 static {
    System.loadLibrary("jjAIS");
 }
            
}
