// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;

import jcas.Standard_Boolean;
import jcas.Standard_Integer;


public class TCollection_BaseSequence extends jcas.Object {

 static {
    System.loadLibrary("jjAIS");
 }
            
native public final boolean IsEmpty();
native public final int Length();
native public final void Reverse();
native public final void Exchange(int I,int J);
public TCollection_BaseSequence() {
}



public native static void FinalizeValue(long anHID);

public void finalize() {
   synchronized(myCasLock) {
     if ( aVirer != 0 ) FinalizeValue(HID);
     HID = 0;
   }
}

}
