// This file is generated by WOK (CPPJini).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.


package jjAIS;

import jcas.Standard_Boolean;


public class TCollection_BasicMapIterator extends jcas.Object {

 static {
    System.loadLibrary("jjAIS");
 }
            
native public final void Reset();
native public final boolean More();
native public final void Next();
public TCollection_BasicMapIterator() {
}



public native static void FinalizeValue(long anHID);

public void finalize() {
   synchronized(myCasLock) {
     if ( aVirer != 0 ) FinalizeValue(HID);
     HID = 0;
   }
}

}
